### ISSUE TITLE
NoMethodError: undefined method  `prepare_statement' started with v 52.2

### ISSUE THREAD

**Issue by Jan-ErikLovlie** [jruby/activerecord-jdbc-adapter#1003]
Our build process runs 'bundle update' and was installing activerecord-jdbcpostgresql-adapter 52.1 (java).  On April 10, 2019 is switched to installing activerecord-jdbcpostgresql-adapter 52.2 (java) and now this error occurs in our application:

ActiveRecord::StatementInvalid (NoMethodError: undefined method `prepare_statement' for #<ActiveRecord::ConnectionAdapters::PostgreSQLJdbcConnection:0xb0800d2>: SELECT ...

The runtime dependencies are being installed:
 activerecord-jdbc-adapter 52.2 (java)
 jdbc-postgres 42.1.4

Also (for activerecord-jdbc-adapter 52.2):
activerecord 5.2.2

**Comment by dr-itz** [comment]
hmm...this is a new addition. I checked the published gem, extracted it and it's there.

It looks like it's loading the old `adapter_java.jar` from the old version of the gem. Can you check where it's loaded from?

**Comment by kares** [comment]
in the mean time you could also try **52.3** although the weirdness still wouldn't be explained.

**Comment by kares** [comment]
no feedback and we have new release(s) since report
