### ISSUE TITLE
Documentation HSQLDB, MariaDB,et al

### ISSUE THREAD

**Issue by rinkevichjm** [jruby/activerecord-jdbc-adapter#1059]
I see that HSQLDB, H2, and derby were supported for prior versions (presumably for rails). The documentation isn't clear as to whether those alternative DBs can be used or whether they need additional support for the current gem version, particularly when used without rails ( I have a client end app I want to port from old Motif/C to JRuby/SWT for UnixSRV5(Sun) and Windows).

**Comment by kares** [comment]
MariaDB is supported the same way Rails supports MySQL (using the `adapter: mysql2`)
for Java DBs such as HSQLDB, H2, Derby since AR 5.0 we do not longer mantain support.
(those only for with AR-JDBC 1.3 which is only Rails <= 4.2 compatible)
