### ISSUE TITLE
Missing File arjdbc/oracle/column

### ISSUE THREAD

**Issue by radpen12** [jruby/activerecord-jdbc-adapter#1128]
Hello!

When I attempt to `require 'arjdbc/oracle/adapter'`, I get a file not found error on line 30: `require 'arjdbc/oracle/column'`
It looks like the file was removed after v5.0.pre1.

I could not find any answers on google or in the open issues.

Am I missing something?

**Comment by enebo** [comment]
@radpen12 Sorry we need to document things properly.  Due to resource constraints we pull backed support
to the big 3 for Rails: postgresql, mysql, and sqlite3.  For Oracle, there is another project you can use: https://github.com/rsim/oracle-enhanced.
