### ISSUE TITLE
Add support for MySQL unsigned columns

### ISSUE THREAD

**Issue by JasonLunn** [jruby/activerecord-jdbc-adapter#373]
Add two way support for MySQL unsigned columns, such that db:schema:dump creates  schema.rb with unsigned columns differentiated from signed columns, and that migrations / db:test:load and friends can all create explicitly unsigned columns.
##

**Comment by kares** [comment]
AR 5.x seems to have done this (with the UnsignedInteger type), AR-JDBC won't support this in AR < 5
