### ISSUE TITLE
Invalid SQL generated when you include a relation from a model backed by a view and try to sort by attribute of the included model

### ISSUE THREAD

**Issue by mikesnare** [jruby/activerecord-jdbc-adapter#410]
If you have a class (say, ViewModel) whose backing table is actually a view and that ViewModel class has an association (belongs_to in this case) to a regular model (say, TableModel), if you try to get instances of that ViewModel and you include the regular model  AND try to order by an attribute of the included model, the SQL that is generated contains a blank column selector.

Example:

``` ruby
# The backing table for this is a SQL Server view, not a table
class ViewModel < ActiveRecord::Base
  belongs_to :table_model
end

# The backing table for this is a SQL Server table, as normal
class TableModel < ActiveRecord::Base
end

# rails console
ViewModel.includes(:table_model).order('table_models.some_attribute')
```

The resulting SQL from this call is one where, prior to the selection of the [view_models].[id] column, there is an inclusion of the "[view_models]." column (note the lack of a column name).  Earlier versions of the mssql adapter added "[view_models].[]" (note the empty column in the brackets).

The start of the SQL looks like this:

``` sql
SELECT [view_models]. AS t0_r0, [view_models].[id] AS t0_r1, ....
```

This fails.  I can work around this by using a joins call in my case, but if I use includes it fails every time.
##

**Comment by rdubya** [comment]
Closing this because it is stale.
