### ISSUE TITLE
(optional) column options

### ISSUE THREAD

**Issue by kares** [jruby/activerecord-jdbc-adapter#423]
support for optional column options (per adapter)

`t.column :string, :ignorecase => true` # e.g. HSQLDB
`t.column :integer, :unsigned => true` # e.g. MySQL related to #373

... really needs to get into ActiveRecord internals

**Comment by JasonLunn** [comment]
With regard to #373, it is worth noting that Rails 5 has gone in a different direction and added support for `t.unsigned_integer` and friends.
See the relevant [unit test](https://github.com/rails/rails/blob/1b8a7b8293e0ff944eb9a5ed84a17b51a87be696/activerecord/test/cases/adapters/mysql2/unsigned_type_test.rb#L45)

**Comment by JasonLunn** [comment]
Actually, I now realize that they're supporting both styles. See [another unit test in that same file](https://github.com/rails/rails/blob/1b8a7b8293e0ff944eb9a5ed84a17b51a87be696/activerecord/test/cases/adapters/mysql2/unsigned_type_test.rb#L58)

**Comment by kares** [comment]
great, thanks for the update. this wasn't really doable on AR-JDBC's end without extensive patching.
