### ISSUE TITLE
ntext column matching start of table name corrupts 'first' query

### ISSUE THREAD

**Issue by gapthemind** [jruby/activerecord-jdbc-adapter#431]
We have a table called 'raw_xml_mcu_transactions' which has an ntext column called raw_xml. When trying to run RawXmlMcuTransaction.first the generated SQL is incorrect.

We expect:

``` sql
SELECT t.* FROM (SELECT ROW_NUMBER() OVER(ORDER BY raw_xml_mcu_transactions.id) AS _row_num ...
```

But we get:

``` sql
SELECT t.* FROM (SELECT ROW_NUMBER() OVER(_mcu_transactions.id)  AS _row_num ...
```

Note the missing "ORDER BY raw_xml". Some debugging has revealed the cause to be an ntext column named raw_xml, and the code in lib/arjdbc/mssql/adapter.rb

The function:

``` ruby
def special_column_names(qualified_table_name)
```

Returns raw_xml as a special column by virtue of its type.

The function

``` ruby
def repair_special_columns(sql)
...
  for column in special_columns
    ...
    sql.gsub!(/ORDER BY \[?#{column}\]?/i, '') 
```

Removes the "ORDER BY raw_xml" from our query. A tighter regular expression

``` ruby
/ORDER BY \[?#{column}\W\]?/i
```

Solves our particular problem, but being unfamiliar with the codebase, I'm unsure of wider implications. That, together with the comment next to the line, make me think that a different patch may be more adequate. If you think that the tighter regular expression is Ok, I'm happy to create a pull request.

Environment
jruby-1.7.2
activerecord-jdbc-adapter-1.3.0.beta2
activerecord-3.2.13
##

**Comment by rdubya** [comment]
Closing this because it is stale.
