### ISSUE TITLE
incorrect .first, .limit and .offset syntax for MSSQL 2000

### ISSUE THREAD

**Issue by Holek** [jruby/activerecord-jdbc-adapter#446]
Hi there,

Using current master, I've noticed a re-introduced bug with SQL Server 2000, where when calling `Model.first` it creates SQL2005 syntax for SQL 2000 as well:

`SELECT _t.* FROM (SELECT [models].*, ROW_NUMBER() OVER (ORDER BY [models].[id]) as _row_num FROM [models] ) as _t WHERE _row_num BETWEEN 1 AND 1`

It fails with:

`ActiveRecord::StatementInvalid: ActiveRecord::JDBCError: 'ROW_NUMBER' is not a recognized function name.`

Using `git bisect` I've managed to pinpoint the commit that has introduced this error: 198067a2692e97832fa0c8faac506e103840ab3d.

Before that commit, AR used to create a proper syntax:
`SELECT TOP 1 [models].* FROM [models] ORDER BY models.id`

This might also propagate to pagination gems that use `limit` and `offset` functions, but I haven't checked that yet.
##

**Comment by rdubya** [comment]
Closing because this is stale.
