### ISSUE TITLE
Timezone issue with MSSQL

### ISSUE THREAD

**Issue by pschambacher** [jruby/activerecord-jdbc-adapter#447]
We're working with a database configured in GMT. When creating an object in the database with a datetime and refetching it, the datetime shifts by 1 hour (basically it considers the date to be UTC instead of GMT).

I'm going to start digging to find the issue myself, but I know there was a refactor of date/time in the past weeks for MSSQL so ...
##

**Comment by rdubya** [comment]
Closing this because it is stale.
