### ISSUE TITLE
Invalid SQL for MSSQL with limit and order - JRuby, Rails4, Scoping and 

### ISSUE THREAD

**Issue by dannycobussen** [jruby/activerecord-jdbc-adapter#473]
Hi,

When I use limit in my scoping, an invalid SQL query is generated. I have an Rails 4 application on JRuby (jruby 1.7.4 (1.9.3p392) 2013-05-16 2390d3b on Java HotSpot(TM) 64-Bit Server VM 1.6.0_51-b11-457-11M4509 [darwin-x86_64]). This is my code in the view:

```
<% related_news = NewsItem.published.accessible_by_user(current_user).with_tags(@news_item.tags).exclude_these(@news_item).limit(5).to_a %>
```

What I'm trying to do here is collecting published NewsItems which are accessible by the user who's logged in with some specific tags, limited to 5 results. So an user is looking at a news item and in a sidebar some related news (by tags) should be shown. 

The query generated from this is:

```
SELECT t.* FROM ( SELECT ROW_NUMBER() OVER(ORDER BY t.important DESC, t.first_published_at DESC) AS _row_num, t.* FROM (SELECT  DISTINCT [news_items].id FROM [news_items] LEFT OUTER JOIN [taggings] ON [taggings].[taggable_id] = [news_items].[id] AND [taggings].[taggable_type] = N'NewsItem' LEFT OUTER JOIN [tags] ON [tags].[id] = [taggings].[tag_id] WHERE [news_items].[state] = N'published' AND [tags].[title] IN (N'mssql') AND ([news_items].[id] NOT IN (1))) AS t ) AS t WHERE t._row_num BETWEEN 1 AND 5
```

Error I'm getting is: invalid column important (and first_published_at).. this make sense because in the subquery it's only selecting the id from news_items and nothing more.

In my scopes I only use ActiveRecord functionality and no custom SQL.
Does anyone know a solution for this problem?

When I chop off the limit it works.. so my workaround now is collecting all the related news (to an array), and take the first 5 items and show them.

Thanks!
##

**Comment by iaddict** [comment]
One more case when query generation fails for mssql on rails 4.2 with arjdbc 1.3.18:
```
> User.limit(10).count
   (3.0ms)  SELECT t.* FROM ( SELECT ROW_NUMBER() OVER(ORDER BY [users].[id]) AS _row_num, COUNT(count_column) FROM (SELECT  1 AS count_column FROM [users]) subquery_for_count ) AS t WHERE t._row_num BETWEEN 1 AND 10
ActiveRecord::JDBCError: com.microsoft.sqlserver.jdbc.SQLServerException: The multi-part identifier "users.id" could not be bound.: SELECT t.* FROM ( SELECT ROW_NUMBER() OVER(ORDER BY [users].[id]) AS _row_num, COUNT(count_column) FROM (SELECT  1 AS count_column FROM [users]) subquery_for_count ) AS t WHERE t._row_num BETWEEN 1 AND 10
```

**Comment by rdubya** [comment]
Closing because this is stale.
