### ISSUE TITLE
MySQL JDBC adapter fails to support utf8mb4 encoding

### ISSUE THREAD

**Issue by jdg** [jruby/activerecord-jdbc-adapter#481]
Hi -

I need to use utf8mb4 encoding in order for MySQL to support 4 byte characters.  A new encoding type, "utf8mb4" was introduced as of MySQL 5.5 to support this.  However when I try and use an encoding type of "utf8mb4" in my database.yml, I receive the following exception after the first SQL request:

ActiveRecord::JDBCError: The driver encountered an unknown error: java.sql.SQLException: Unsupported character encoding 'utf8mb4'.

Am I missing something?  Shouldn't this just "pass through" and work appropriately?

**Comment by sungine** [comment]
hey guys ! I just find a way to avoid that issue.
my error version of jdbc.url is
` jdbc:mysql://x.x.x.x:3306/db?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8mb4`
while i change the url to 
`jdbc:mysql://x.x.x.x:3306/db?createDatabaseIfNotExist=true&amp;useUnicode=true&amp;characterEncoding=utf8mb4&amp;`

It works!!

**Comment by kennycason** [comment]
@sungine I did not expect that to work, but out of desperation, I tried it, and it did in fact work. :)

**Comment by MewX** [comment]
The comment above didnt work for me, I'm now using this:

```
dbc:mysql://x.x.x.x:3306/db?createDatabaseIfNotExist=true&useUnicode=true&character_set_server=utf8mb4
```
