### ISSUE TITLE
"stack level too deep" on "rake db:create:all" in version 1.3.x

### ISSUE THREAD

**Issue by marutosi** [jruby/activerecord-jdbc-adapter#493]
Version 1.2.x passes, but 1.3.x fails.

1.2.x

http://www.redmine.org/builds/logs/build_2.3-stable_mysql_jruby-1.7.2_109.html

1.3.x

http://www.redmine.org/builds/logs/build_trunk_mysql_jruby-1.7.6_1612.html

```
$ bundle exec rake ci --trace
** Invoke ci (first_time)
** Execute ci
** Invoke ci:setup (first_time)
** Execute ci:setup
** Invoke tmp:clear (first_time)
** Invoke tmp:sessions:clear (first_time)
** Execute tmp:sessions:clear
** Invoke tmp:cache:clear (first_time)
** Execute tmp:cache:clear
** Invoke tmp:sockets:clear (first_time)
** Execute tmp:sockets:clear
** Execute tmp:clear
** Invoke log:clear (first_time)
** Execute log:clear
** Invoke db:create:all (first_time)
** Invoke db:load_config (first_time)
** Execute db:load_config
** Execute db:create:all
rake aborted!
stack level too deep
/home/xxxx/.rvm/gems/jruby-1.7.4/gems/activerecord-3.2.15/lib/active_record/railties/databases.rake:184:in `local_database?'
/home/xxxx/.rvm/gems/jruby-1.7.4/gems/activerecord-3.2.15/lib/active_record/railties/databases.rake:52:in `(root)'
org/jruby/RubyHash.java:1375:in `each_value'
/home/xxxx/.rvm/gems/jruby-1.7.4/gems/activerecord-3.2.15/lib/active_record/railties/databases.rake:38:in `(root)'
org/jruby/RubyProc.java:255:in `call'
/home/xxxx/.rvm/gems/jruby-1.7.4/gems/rake-10.0.4/lib/rake/task.rb:246:in `execute'
```

**Comment by johonas** [comment]
I have the same Problem using version 1.3.17 and JRuby-Version 1.7.12.
Version 1.2.9 is working fine.
There is no jdbc.rake under "lib/rasks".

Here's my stacktrace:

-- create_table(:users)
SystemStackError: stack level too deep
	from ---/vendor/bundle/gems/activerecord-3.2.19/lib/active_record/migration.rb:438:in `say_with_time'
	from /opt/---/jruby/jruby-1.7.12/lib/ruby/1.9/benchmark.rb:280:in `measure'
	from ---/vendor/bundle/gems/activerecord-3.2.19/lib/active_record/migration.rb:438:in `say_with_time'
	from ---/vendor/bundle/gems/activerecord-3.2.19/lib/active_record/migration.rb:458:in `method_missing'
	from ---/db/migrate/20130107165555_create_users.rb:3:in `change'
	from (irb):60:in `evaluate'
	from org/jruby/RubyKernel.java:1101:in `eval'
	from org/jruby/RubyKernel.java:1501:in `loop'
	from org/jruby/RubyKernel.java:1264:in `catch'
	from org/jruby/RubyKernel.java:1264:in `catch'
	from ---/vendor/bundle/gems/railties-3.2.19/lib/rails/commands/console.rb:47:in `start'
	from ---/vendor/bundle/gems/railties-3.2.19/lib/rails/commands/console.rb:8:in `start'
	from ---/vendor/bundle/gems/railties-3.2.19/lib/rails/commands.rb:41:in `(root)'
	from org/jruby/RubyKernel.java:1065:in `require'
	from script/rails:6:in `(root)'
