### ISSUE TITLE
Support for MSSQL lock hints

### ISSUE THREAD

**Issue by pschambacher** [jruby/activerecord-jdbc-adapter#494]
On MSSQL using SELECT, UPDATE or DELETE will use a PAGELOCK by default.

I assume this is supposed to be a smart thing but it's mainly a pain in the rear end in practice. If you have 2 threads fetching users in the same page, one will be stuck until the other is done. Make it 50 threads and the 50th can wait a few seconds.

To solve this, you need to give a hint to MSSQL to lower the lock to something smaller (or nothing at all). We end up using NOLOCK in most of the select (ROWLOCK if you actually want to lock the object in a transaction) and ROWLOCK for UPDATE and DELETE to lock only the object you want to interact with.

When it was only a few requests here and there, we coded a couple of gsub to apply on a SQL string. What we would do is to generate the SQL request using .to_sql on a fetch and then append the NOLOCK after the WHERE table and the JOIN tables. We did something similar for UPDATE using AREL and the UpdateManager.

Now we end up having these things growing everywhere in the application and it starts to feel like we're not using ActiveRecord and we're starting to do PHP ...

I'd like to add the support for this in the MSSQL adapter. Ideally just chaining hint(:nolock) or hint(:rowlock) in activerecord and be done with it (also maybe I could set it as a default). My issue there is that I don't know the adapter and arel code enough to start right away. If you guys have some pointers to help me I can start working on that.
# 

you can support MS-SQL features at [BountySource](https://www.bountysource.com/issues/1346717-support-for-mssql-lock-hints)
##

**Comment by rdubya** [comment]
Closing this because it is stale. Also, our MSSQL support for Rails 5+ is a fork of activerecord-sqlserver-adapter so it may work now.
