### ISSUE TITLE
MSSQL - NATIVE_DATABASE_TYPES does not exist

### ISSUE THREAD

**Issue by stonehz** [jruby/activerecord-jdbc-adapter#508]
In my attempt to override certain default data types 
I discovered that NATIVE_DATABASE_TYPES does not exist for MSSQL.
Checking here:
https://github.com/jruby/activerecord-jdbc-adapter/blob/master/lib/arjdbc/mssql/adapter.rb

All other DBs seem to have one (mysql, postgres,oracle,sqllite3,etc)

Is there another way to override data_types?

Thank you in advance!

```
JDBC version 1.3.3
JRuby 1.7.5
Rails 4.00
````

**Comment by kares** [comment]
closing due https://github.com/jruby/activerecord-jdbc-adapter/commit/230f9c5f0c144a292322b36ed10bfd383514abbe
