### ISSUE TITLE
postgresql numeric type without scale or precision

### ISSUE THREAD

**Issue by til** [jruby/activerecord-jdbc-adapter#55]
When creating a column of type :decimal without specifying scale or precision, the scale defaults to 0 and the fractional part of the number is lost. The value is loaded as Fixnum.

Retrieving the same database value with mri ruby and the postgresql adapter behaves as expected: the value is loaded as BigDecimal and still contains the fractional part.

I created a failing test case: https://github.com/til/activerecord-jdbc-adapter/commit/c72b59d31b5747499196fd04a45fb2573b2964e9

**Comment by amiracam** [comment]
I seem to have a related issue in that a column in our pg database (a migration from oracle to pg via Ruby Sequel script) is defined as numeric(14,7) but when inquired later via jdbc api, i.e. get_precision and get_scale both return 0.
