### ISSUE TITLE
NoMethodError: undefined method `type' for "character varying(255)":String with ActiveRecord 4.2.0.beta1

### ISSUE THREAD

**Issue by donv** [jruby/activerecord-jdbc-adapter#575]
Starting my Rails 4.1 app with Rails 4.2.0.beta1 gives this error:

    NoMethodError: undefined method `type' for "character varying(255)":String

Looks like the column type is now an object of class ActiveRecord::Type::Value instead of a String.

**Comment by donv** [comment]
I tried looking at this for PostgreSQL, but it is extremely slow going.  Any help is appreciated.

**Comment by donv** [comment]
@edpaget @prathamesh-sonpatki do you have any changes that are not merged with master?

**Comment by prathamesh-sonpatki** [comment]
@donv No. All my commits are in the master.

**Comment by donv** [comment]
I need to chat with someone to get any progress.  What channel are you guys on?  IRC #jruby ?

**Comment by kares** [comment]
master is far from a release ... maybe a pre. this in particular might end up beinghandled differently on master than it would on 1.3 since we tend to do our very-own JDBC type-casts. all thecode done by Prathamesh should be on 1-3-stable (as well) ...

**Comment by andrewvc** [comment]
Thanks for looking into this guys :)

**Comment by kares** [comment]
.. this has changed since 4.2 beta1 - **1-3-stable** now handles type-casting now better aligned with Rails

**Comment by Xanthus** [comment]
Does that mean 1-3-stable shouldn't have this problem anymore? I checked it out and the tests are still failing with the same error so I think I'm misunderstanding.

**Comment by kares** [comment]
my bad - thought this to be SQLite3 adapter specific - in general no, type support is not finished (in **1.3.16**) and requires more work to support all adapters available with AR-JDBC as well as "generic" type resolution for *adapter: jdbc* ... MySQL and SQLite might be working at this point - could use more real-world testing

**Comment by kares** [comment]
should be fixed now (feel free to try out **1-3-stable** or 1.3.18 when its released) thanks to @donv

**Comment by ismith** [comment]
I'm seeing something I think is this error.  activerecord-jdbc-adapter 1.3.18, activerecord 4.2.4 or 4.1.13.  `rake db:schema:dump` results in:

```
Could not dump table "[tablename]" because of following NoMethodError
   undefined method `type' for "int(10) unsigned":String
```
for each of my tables.

(Hadn't previously been using AR in this project, so I don't have a known-good version to provide yet.)

**Comment by ismith** [comment]
Hmm, and today I can't repro that - it seems to work.  Sorry - will keep an eye out for it.
