### ISSUE TITLE
config[:insert_returning] = false might not always work

### ISSUE THREAD

**Issue by kares** [jruby/activerecord-jdbc-adapter#579]
can be disabled (_insert_returning_ defaults to true) since 1.3.10 but there are failures that need a review

reproducable with: **PREPARED_STATEMENTS=true INSERT_RETURNING=false**
##

**Comment by dr-itz** [comment]
Tests are passing since #936. I think this could be closed..

**Comment by kares** [comment]
thanks, and its a non-fix for 1.3 (AR up to 4.x)
