### ISSUE TITLE
I would like to help get things fixed on 4.2

### ISSUE THREAD

**Issue by sgrif** [jruby/activerecord-jdbc-adapter#604]
@kares I can't seem to find a way to get in touch with you privately. I'm the guy who made most of the structural changes that are breaking on master, would like to assist with getting it resolved. We could fix them pretty quickly by copy pasting some code, but we would like to solve the problem for the long term so we don't have to keep doing this.

I think we would be better served in the long run to have the JDBC Sqlite3 adapter subclass the AR Sqlite3 adapter (and Mysql, PG, etc), and then mix in a module that overrides the JDBC specific stuff. It seems like most of this code (types, column classes, etc) shouldn't need JDBC specific stuff. Would love to talk about it further with you. My email address is on my profile.

**Comment by kares** [comment]
anyone @sgrif @prathamesh-sonpatki still planning to help out some (more) towards 4.2 compatibility ?

**Comment by prathamesh-sonpatki** [comment]
@kares Sorry got busy. I would like to finish it. I think we have the complete list of issues here right https://github.com/jruby/activerecord-jdbc-adapter/issues/599#issue-48070414

**Comment by kares** [comment]
@prathamesh-sonpatki hopefully - let the test failures (and issue reports) guide you ...

**Comment by prathamesh-sonpatki** [comment]
@kares Thanks. Can you please check https://gist.github.com/prathamesh-sonpatki/c5d7fcc7d438fc571305. I am getting error while running the build.

**Comment by kares** [comment]
on master you'll need to build the *adapter_java.jar* (it's no longer committed in git - still there on 1-3-stable ... that's were you probably worked the last time) try `mvn package` or `gem install jdbc-postgres jdbc-mysql` + check for a rake task - but I'm not sure how I left things ... trying to compile the extension auto-magically (without Maven)
