### ISSUE TITLE
find_by_sql gets passed an ActiveRecord::Result instance, which does not respond to collect!()

### ISSUE THREAD

**Issue by benissimo** [jruby/activerecord-jdbc-adapter#607]
Using jruby 1.7.6, activerecord 3.2.21, db2 10.5, when I run, for example:

  Property.first

or

  Property.order(:property_id).limit(3)

or seemingly any combination of Arel, it results in an exception:

NoMethodError: undefined method `collect!' for #<ActiveRecord::Result:0x5fca210b>
from .../rails/vendor/bundle/jruby/1.9/gems/activerecord-3.2.21/lib/active_record/querying.rb:38:in `find_by_sql'

My workaround for this is:

    module ActiveRecord
      module Querying
        def find_by_sql(sql, binds = [])
          logging_query_plan do
            # connection.select_all(sanitize_sql(sql), "#{name} Load", binds).collect! { |record| instantiate(record) }
            # activerecord-jdbc-adapter returns an ActiveRecord::Result instance, which
            # responds to #collect but not #collect!
            connection.select_all(sanitize_sql(sql), "#{name} Load", binds).collect { |record| instantiate(record) }
          end
        end
      end
    end

ie. I rewrite find_by_sql so that it uses collect() instead of collect!().
ActiveRecord::Result instances mix in Enumerable, so they have access to collect().
They do not have access to collect!().

Question: should find_by_sql() get invoked in these cases?
If so, should ActiveRecord::Result instances have access to collect!()?

I'm not sure if this is a bug or if somehow my setup is calling find_by_sql() when it shouldn't.

Has anyone else run into this issue? Please advise, thanks!

**Comment by kares** [comment]
fixed on **1-3-stable** as https://github.com/kares/activerecord-jdbc-adapter/commit/36e171cabe374ae86fe16fa69ce8146b02fa3d1d ... available since **1.3.14**
