### ISSUE TITLE
Java::JavaLang::UnsatisfiedLinkError: org.sqlite.core.NativeDB._open(Ljava/lang/String;I)V

### ISSUE THREAD

**Issue by jomendoz** [jruby/activerecord-jdbc-adapter#610]
Hi,

I ran into this problem and it seems to be related to some native library that doesn't load. I've been working on one project in two different linux distributions (archlinux and ubuntu trusty 14.4) and I used the very same packages. In the former, everything work smoothly, but in Ubuntu the error prompts every time I use ActiveRecord for manipulating SQLite3.

I got in the two boxes:
RVM 1.26.8
JRuby 1.7.18
ActiveRecord 4.1.8
activerecord-jdbcsqlite3-adapter 1.3.13

Errors:
https://gist.github.com/jomendoz/e04e0722772353b4942b

Libs:
https://gist.github.com/jomendoz/7bce15e928c98f8f5c0d

**Comment by kares** [comment]
this seems as a bug in **jdbc-sqlite3** itself, which we do not maintain at the source level - we're only releasing the .jar driver artifacts as a gem. for completeness JVM details and jdbc-sqlite3 version might be interesting for the users running into this, thanks!
