### ISSUE TITLE
Bundle failure using master branch

### ISSUE THREAD

**Issue by splattael** [jruby/activerecord-jdbc-adapter#614]
Hi,

while hunting build failures for Rails on jruby (https://travis-ci.org/rails/rails/jobs/47897879) I've noticed
that currently it's not possible to bundle `activerecord-jdbc-adapter` on its `master` branch.

Example Gemfile:

```ruby
gem 'activerecord-jdbcsqlite3-adapter', github: 'jruby/activerecord-jdbc-adapter', branch: 'master'
gem 'activerecord-jdbcmysql-adapter', github: 'jruby/activerecord-jdbc-adapter', branch: 'master'
gem 'activerecord-jdbcpostgresql-adapter', github: 'jruby/activerecord-jdbc-adapter', branch: 'master'
```

I've setup a test repository at https://github.com/splattael/ar-jdbc-bundle-test which tries to bundle 3 different versions:
* gem 1.3.13
* `v1.3.13` branch
* `master` branch

Bundling on Travis works for the gem and the `v1.3.13` branch but fails for `master`:
https://travis-ci.org/splattael/ar-jdbc-bundle-test/builds/47902674

Can someone help me here?

For now, I will try to "revert" rails/rails#12107 which introduced testing against AR-JDBC master.

**Comment by kares** [comment]
right, on master we're trying to avoid having to commit the *adapter_java.jar* every time we change a native .java source ... so far I could not get it building correctly on those `:git` gem installs ;( - I sure appreciate any help I can get. 

you can reference **1-3-stable** branch which is the current stable release where it still works the "old" way.

**Comment by splattael** [comment]
@kares Thanks for your answer.

So, the most stable way for Rails tests is now to use the stable branch OR the latest gem, right?

**Comment by kares** [comment]
yep, but we're unfortunately not up-to-date with 4.2 (internal) refactorings - so that won't work either way ;(

**Comment by splattael** [comment]
@kares Gotcha. No worries! :)
My point is that I'd like to see at least some failures when running Rails tests on JRuby rather than aborting in the "bundler" stage. Using latest gem release is the safest option here.

**Comment by kares** [comment]
builds should now once again work against master (as well) ... there's a few tricks were playing to resolve native extension compile dependencies (.jars) but on travis-ci it should all work just fine as is already, thx!

**Comment by splattael** [comment]
@kares Thank you for your efforts :+1:
