### ISSUE TITLE
Bigints aren't being casted properly for schemas

### ISSUE THREAD

**Issue by zanker** [jruby/activerecord-jdbc-adapter#617]
This is happening with activerecord-4.2.0, activerecord-jdbc-adapter/activerecord-jdbcmysql-adapter 1.3.13 and jdbc-mysql 5.1.33. I tried to see about fixing it, but I got stuck on some sort of black magic within the MRI code set that calls `extract_limit` and wasn't able to trace the rest.

The summary of what I've found:

In pre-4.2 AR, the extraction for creating a schema.rb file would use `extract_limit` from the column class (lib/arjdbc/mysql/column.rb). In 4.2 AR, this has been moved to the `lookup_cast_type` method (in lib/active_record/connection_adapters/abstract_adapter.rb), which eventually calls `extract_limit` in the same file and does a regex.

In JRuby, this means `BIGINT(20)` has a limit of 20 and it runs through the schema dump, where it hits the `type_to_sql` conversion, sees a 20 and blows up. The old `extract_limit` isn't called because it's under the `Column` class and not the `AbstractAdapter` one.

On MRI, it turns `BIGINT(20)` into a limit of 8 properly, which doesn't blow up. I was unable to find where in MRI it's overriding `extract_limit` to do the proper conversions, as doing a grep on all of my gems wasn't able to find the method.

Simple case to replicate:

```ruby
create_table :foo_bar do |t|
  t.integer :bad_int, limit: 8
end
```

If you run a `rake db:migrate` you will see a `BIGINT(20)` in the DB which is correct. If you run a `be rake db:schema:dump` in MRI, you get a `t.integer :bad_int, limit: 8` and on JRuby you will get `t.integer :bad_int, limit: 20`. If you run `be rake db:test:clone` on JRuby, it errors because of that.

**Comment by kares** [comment]
Thanks Zachary, we do have some (ActiveRecord) code to review to support 4.2 fully #599 ... I've decided to print a warning in the next 1.3 release so people are aware of us NOT fully supporting Rails 4.2 (and maybe can help us push it in as well)

**Comment by kares** [comment]
... should be fine with https://github.com/jruby/activerecord-jdbc-adapter/commit/fe11cac0e75007333cfc0c2e40e522872d1ba38b ... let us know otherwise, thanks!
