### ISSUE TITLE
Validates numericality and uniqueness throws exception for non-numeric value

### ISSUE THREAD

**Issue by F2Andy** [jruby/activerecord-jdbc-adapter#618]
Say I have a model wit this validation:

```
class Post < ActiveRecord::Base
  validates :count, :presence => true, :numericality => true, :uniqueness => true
end
```

If I pass a value to count that is not numeric and then try to save the record, Rails will test for uniqueness by accessing the database, which will then object that it has been given the wrong type of data for an integer field, for example throwing up:

`ActiveRecord::StatementInvalid: ActiveRecord::JDBCError: org.postgresql.util.PSQLException: ERROR: invalid input syntax for integer: "abc"`

This worked properly (i.e., save failed gracefully, adding an appropriate error message to the record) in Rails 4.1.

This was tested on a new Rails 4.2 project (JRuby, PostgreSQL), with a single model set up like this:

rails g scaffold Post name:string comment:text count:integer

**Comment by kares** [comment]
expecting this issue to be fine with **1.3.17** ... please confirm (if not feel free to re-open), thanks!
