### ISSUE TITLE
Informix adapter undefined method 'column_types' with Rails 4.x

### ISSUE THREAD

**Issue by shado23** [jruby/activerecord-jdbc-adapter#622]
```
> Image.count
   (97.0ms)  SELECT COUNT(*) FROM images 
NoMethodError: undefined method `column_types' for [{"(count(*))"=>#><BigDecimal:5eb2172,'114234.0',7(8)>}]:Array
from /usr/local/Cellar/jruby/1.7.19/libexec/lib/ruby/gems/shared/gems/activerecord-4.1.9/lib/active_record/relation/calculations.rb:268:in `execute_simple_calculation'
```

This looks like whatever was done to fix #262 was not done for Informix.
(Rails 3.x works as expected.)

**Comment by kares** [comment]
thanks @shado23 ...there's no one on the team testing against Informix, thus I encourage you look into it

**Comment by shado23** [comment]
Fair enough. I'll see if I can make the time to dig into it.

It looks like it might simply be caused by the Informix Column and Adapter classes not inheriting from JdbcColumn / JdbcAdapter, as all the others do.

**Comment by kares** [comment]
closing https://github.com/jruby/activerecord-jdbc-adapter/pull/627#issuecomment-77804849
