### ISSUE TITLE
Rails 4.2, boolean-type MySQL columns coming accross as 0/1, not true/false

### ISSUE THREAD

**Issue by jrochkind** [jruby/activerecord-jdbc-adapter#626]
Is this one of the known problems in 4.2? If so, can be closed, but reporting just in case. 

I have a column created in a migration as "t.boolean", in a MySQL database. 

After fetching an object from this table, in Rails 4.1 and previous, the values show up as either boolean true or false. In Rails 4.2, the values show up as integer 0 or 1. 

Of course, this causes bugs from software expecting true or false. 

I guess I can probably work around this by some custom hook in my model that converts 0 and 1 to true and false on read, but it's messy.

**Comment by kares** [comment]
there's probably more casting related regressions due AR changing its type-casting its guts in 4.2 ... we're still waiting for contributors to finish up or sponsor these: https://github.com/jruby/activerecord-jdbc-adapter/issues/599

**Comment by jrochkind** [comment]
Sweet, thanks!  Is there an ETA for a release that includes these improvements?
