### ISSUE TITLE
Rails 4.2, MySQL: cannot use 't.references' in migration

### ISSUE THREAD

**Issue by bulzak** [jruby/activerecord-jdbc-adapter#629]
So I generated a Rails migration using the 'references' keyword to create the association between model First and Second. I called:
```
rails g model second name:string first:references
```

And I got this:
```
class CreateSeconds < ActiveRecord::Migration
  def change
    create_table :seconds do |t|
      t.string :name
      t.references :first, index: true

      t.timestamps null: false
    end
    add_foreign_key :seconds, :firsts
  end
end
```

It fails like so:
```
command: rake db:migrate
== 20150311070101 CreateSeconds: migrating ====================================
-- create_table(:seconds)
#<Class:0x3e73138a>: An error has occurred, all later migrations canceled:

Index name 'index_seconds_on_first_id' on table 'seconds' already exists
```

It fails before the add_foreign_key call, complaining that the `Index name 'index_seconds_on_first_id' on table 'seconds' already exists`. The current walkaround is to remove the `t.references` call and replace it by `add_reference :seconds, :first, index: true` outside of `create_table`. So what is going on, why is t.references creating the index twice?

Also, the add_foreign_key method doesn't do anything at the moment.

**Comment by kares** [comment]
should be fixed now on **1-3-stable** with https://github.com/jruby/activerecord-jdbc-adapter/pull/631 in place ... feel free to re-open if not, thanks!
