### ISSUE TITLE
activerecord-jdbc-adapter 1.3.16 is incompatible with Ruby18

### ISSUE THREAD

**Issue by batter** [jruby/activerecord-jdbc-adapter#641]
due to the JSON-style hash syntax on [This line](https://github.com/jruby/activerecord-jdbc-adapter/blob/master/lib/arjdbc/postgresql/adapter.rb#L214) that was merged in by [this merge](https://github.com/jruby/activerecord-jdbc-adapter/commit/8db48e98c4d3184e972e9821f425133ee529fec0#diff-2112926371df9c6109e518a24b32b6b8R214).

The gem should either specify a [`required_ruby_version`](http://guides.rubygems.org/specification-reference/#required_ruby_version=) of `'1.9'` on it's gemspec, or the syntax of that hash could be changed to use the good old hash-rocket syntax (`{:key => value}` instead of `{key: value}`).  Thanks for the gem!

**Comment by kares** [comment]
interestingly travis-ci testing revealed nothing while running against AR 3.2 JRuby 1.7.16 in 1.8.7 mode
... while this will for sure be fixed, any details/traces on your environment might be useful as well, thx!

**Comment by batter** [comment]
I only noticed this because I had [a build of a gem I maintain that was using this gem to test against JRuby in 1.8 mode on Travis](https://travis-ci.org/airblade/paper_trail/builds/58792325). I got it passing again by [limiting the version number of the dependency to 1.3.15 again](https://travis-ci.org/airblade/paper_trail/builds/58817331).

**Comment by kares** [comment]
fixed on **1-3-stable** branch, you should be able to use that with `:git` until next 1.3.x release happens

**Comment by batter** [comment]
Cheers
