### ISSUE TITLE
Broken ordering on an aggregate in MSSQL

### ISSUE THREAD

**Issue by fpauser** [jruby/activerecord-jdbc-adapter#645]
We see the same wrong behavior as described in #532. 

When using `limit` and `offset` the order-part gets wrapped in `MIN()` which breaks the query.

Versions we tried that fail: 1.3.16, 1.3.14 and 1.3.6
Last working version: 1.3.5

**Comment by kares** [comment]
re-opened #532 and closing this one as duplicate
