### ISSUE TITLE
db:drop / db:create do not work

### ISSUE THREAD

**Issue by jkuchta** [jruby/activerecord-jdbc-adapter#648]
rails 4.0.13
activerecord-jdbc-adapter 1.3.16
activerecord-jdbcmysql-adapter 1.3.16
jdbc-mysql 5.1.22

When using db:drop/db:create with the below configuration, I receive the error 

`Couldn't create database for {"adapter"=>"", "encoding"=>"utf8", "username"=>"root", "password"=>"xxx", "database"=>"sample_test", "driver"=>"com.mysql.jdbc.Driver", "url"=>"jdbc:mysql://localhost:3306/sample_test"}`

```
test:
  adapter: jdbc
  encoding: utf8
  username: root
  password: xxx
  database: sample_test
  driver: com.mysql.jdbc.Driver
  url: 'jdbc:mysql://localhost:3306/sample_test'

**Comment by kares** [comment]
try using **adapter: mysql** instead so it can pick up the correct rake tasks, closing as we're going to be deprecating **adapter: jdbc** for uses such as yours anyways. thanks!
