### ISSUE TITLE
add_foreign_key silently does not create foreign keys

### ISSUE THREAD

**Issue by mjc** [jruby/activerecord-jdbc-adapter#656]
I'm working up a test case, but I'm curious if this is expected since 4.2 support is not done yet?

**Comment by kares** [comment]
@mjc probably ... did some work on **1-3-stable** lately please try against it (as well) if possible
although none was explicitly `add_foreign_key` related ... we will definitely need more details here :)

**Comment by mjc** [comment]
Still does not generate foreign keys on 46794950527bdef4a3c703fd5973e71a335d28cf.

I'll try and make a reduced test case today.

**Comment by mjc** [comment]
[Test case](https://github.com/mjc/arjdbc-fk)

**Comment by mjc** [comment]
above commit does not work in the test case:
```
NoMethodError: private method `warn' called for ArJdbc:Module
/Users/mjc/.gem/ruby/2.2.2/bundler/gems/activerecord-jdbc-adapter-21329bf3ccb4/lib/arjdbc.rb:23:in `<top (required)>'
/Users/mjc/.gem/ruby/2.2.2/bundler/gems/activerecord-jdbc-adapter-21329bf3ccb4/lib/activerecord-jdbc-adapter.rb:1:in `require'
/Users/mjc/.gem/ruby/2.2.2/bundler/gems/activerecord-jdbc-adapter-21329bf3ccb4/lib/activerecord-jdbc-adapter.rb:1:in `<top (required)>'
/Users/mjc/.gem/ruby/2.2.2/gems/bundler-1.10.3/lib/bundler/runtime.rb:76:in `require'
/Users/mjc/.gem/ruby/2.2.2/gems/bundler-1.10.3/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
/Users/mjc/.gem/ruby/2.2.2/gems/bundler-1.10.3/lib/bundler/runtime.rb:72:in `each'
/Users/mjc/.gem/ruby/2.2.2/gems/bundler-1.10.3/lib/bundler/runtime.rb:72:in `block in require'
/Users/mjc/.gem/ruby/2.2.2/gems/bundler-1.10.3/lib/bundler/runtime.rb:61:in `each'
/Users/mjc/.gem/ruby/2.2.2/gems/bundler-1.10.3/lib/bundler/runtime.rb:61:in `require'
/Users/mjc/.gem/ruby/2.2.2/gems/bundler-1.10.3/lib/bundler.rb:134:in `require'
/Users/mjc/Sites/arjdbc-fk/config/application.rb:7:in `<top (required)>'
/Users/mjc/Sites/arjdbc-fk/Rakefile:4:in `require'
/Users/mjc/Sites/arjdbc-fk/Rakefile:4:in `<top (required)>'
(See full trace by running task with --trace)
```

Also it is mysql foreign key support I am trying to use rather than postgres.

**Comment by mjc** [comment]
f161ccb may fix this for postgres but it does not fix it for mysql, which is my primary test case.  Thanks for responding so quickly though :+1:

**Comment by kares** [comment]
@mjc do not get use to it much ... you had a good timing catching me baking an AR-JDBC release :)

please test if you can and let us know if you run into any issues using **1-3-stable**
