### ISSUE TITLE
Broken link in README.md

### ISSUE THREAD

**Issue by digitalextremist** [jruby/activerecord-jdbc-adapter#657]
The link to this, is dead:

http://dev.mysql.com/usingmysql/java/

It seems like it might be a link to this, now:

http://dev.mysql.com/doc/connector-j/en/index.html

But I'm not sure, only that the link is broken.

**Comment by kares** [comment]
thank you, I do not see this link in the *README.md* ... could you point us where its from?

**Comment by digitalextremist** [comment]
Sorry, it is actually in a subordinate `README.md` here:

https://github.com/jruby/activerecord-jdbc-adapter/blob/master/jdbc-mysql/README.md

**Comment by kares** [comment]
ok, thanks ... updated - feel free to edit and submit a PR on your own (e.g. using GH's UI) next time

**Comment by digitalextremist** [comment]
Will do!
