### ISSUE TITLE
jruby migration failure

### ISSUE THREAD

**Issue by luckybarbra** [jruby/activerecord-jdbc-adapter#658]
NOTE: ActiveRecord 4.2 is not (yet) fully supported by AR-JDBC, please help us finish 4.2 support - check http://bit.ly/jruby-42 for starters

**Comment by kares** [comment]
well yeah - how else should we report users that 4.2 might not work fully ?!
... if you have issues please do a complete report on observed behaviour - warning will be there until #599

**Comment by luckybarbra** [comment]
Kares, any help on how i can do a complete report? I wish i can get more direct advise on how to get rid of this problem, say a command to run in my terminal or more direct steps to follow,,,,,,

**Comment by kares** [comment]
@luckybarbra sorry I'm not sure what you're asking for ... completing 4.2 needs dedicated work, there's no step-by-step guide on how to do it (there's details on the linked issue, otherwise follow our failing tests)
