### ISSUE TITLE
NoMethodError: undefined method `compile' for #<String:0xc6ba147>

### ISSUE THREAD

**Issue by donv** [jruby/activerecord-jdbc-adapter#660]
As seen in travis:

https://travis-ci.org/jruby/activerecord-jdbc-adapter/jobs/68947526#L1519

Anybody looked at this yet?

**Comment by kares** [comment]
should be a duplicate of https://github.com/jruby/activerecord-jdbc-adapter/issues/662 ... please confirm

**Comment by donv** [comment]
Yes, should go away when you merge the recent changes form 1-3-stable.
