### ISSUE TITLE
Get `type_cast`working with Derby

### ISSUE THREAD

**Issue by donv** [jruby/activerecord-jdbc-adapter#662]
Example in travis:

https://travis-ci.org/jruby/activerecord-jdbc-adapter/jobs/68947526#L1053

I have a customer waiting for this to upgrade a production app to AR 4.2, so I am highly motivated to help out.

Any help is very greatly appreciated.

**Comment by kares** [comment]
most of this is done for MySQL/PostgreSQL/SQLite already (and a lot more to [smooth out](https://github.com/jruby/activerecord-jdbc-adapter/issues/599) 4.2 support - reviewing commits should help) but it still needs to be done for the JDBC generic case - somehow that it works "as good" as the previous version, than likely all specific adapters will need to get revisited. the "fast" (and furious) alternative would be to hack it together for Derby only, although even a working version might not be a complete one (we probably need to backport more tests for new behaviour such as FKs).

**Comment by donv** [comment]
Hi @kares !

Thanks for getting back to me.  Can you outline what needs to be done to get a working driver for Derby?  My starting point is that "lib/arjdbc/derby/adapter.rb" needs a "type_cast" method in the ```ColumnMethods``` module.  Is that right?  My next idea is to copy a ```type_cast```method from another adapter like postgresql and tweak it to work with Derby.

Does this sound right?

Any other things that are likely to come up?

You mentioned backporting tests to increase confidence.  Where would we backport these tests from?

**Comment by kares** [comment]
sorry, hints on my part ... do not hold the details really. 
know what to do when I am at it - thus can not guide you in much detail without trying. your plan sound like a good start. reviewing AR 4.2 and AR-JDBC commits would be the next phase. test might come from AR itself - probably loosely, but do not worry about it if you do not care for "full" compatibility.

**Comment by donv** [comment]
OK, I have read through a lot of the code, and it seems every adapter solves the problem differently.  Is that right?

Anyway, it looks like the base JdbcAdapter calls the "columns" method on the "@connection" which is in RubyJdbcConnection which uses JDBC to find the columns and then call "new" on the Column class.  The default JdbcColumn class has an "initialize" method that **does** handle the new cast_type option, but the "columns" method of RubyJdbcConnection does not send the argument.

Should we not change RubyJdbcConnection#columns to send the "cast_type" argument, or change JdbcColumn#initialize to add the missing "cast_type" argument if it is missing?

Please bear with me.  I am still learning the code.  There is a lot :)

**Comment by donv** [comment]
This has now been fixed and landed on 1-3-stable.  @kares will merge to master.
