### ISSUE TITLE
Column information is cached even after "reset_column_information" is called for Derby

### ISSUE THREAD

**Issue by donv** [jruby/activerecord-jdbc-adapter#667]
Illustrated by test ```test_boolean_emulation_can_be_disabled```.

https://travis-ci.org/jruby/activerecord-jdbc-adapter/jobs/71295595#L1350

@kares I have no clue what is happening here.  I see the caches getting cleared, but suddenly they are back.

**Comment by kares** [comment]
me neither esp. as it works with other AR versions ... this is not unusual with AR-JDBC development - surprises constantly pop-up esp. when there's a "new" AR involved - feel free to proceed tracing down.

**Comment by donv** [comment]
Fixed it!  ActiveRecord is caching type_map information even after a call to reset_column_information.

Added a reset of the type_map to the Derby adapter.
