### ISSUE TITLE
Binaries are unescaped twice with AR42 + PostgreSQL + prepared statements

### ISSUE THREAD

**Issue by donv** [jruby/activerecord-jdbc-adapter#675]
Failing test:  https://travis-ci.org/jruby/activerecord-jdbc-adapter/jobs/71944362#L624

Initial investigation shows that the binary content comes **unescaped** from RubyJdbcConnection (@connection.execute_query(sql, binds)) to ActiveRecord::ConnectionAdapters::JdbcAdapter#exec_query when using prepared statements:

https://github.com/jruby/activerecord-jdbc-adapter/blob/1-3-stable/lib/arjdbc/jdbc/adapter.rb#L449

When not using prepared statements, the result **IS** escaped.

We need to investigate how to avoid unescaping the result when using prepared statements.

I have not found an obvious place to do that, yet, and all help is appreciated.

**Comment by donv** [comment]
@kares any idea where we should put this logic?

**Comment by donv** [comment]
My current plan is to make RubyJdbcConnection return an ActiveRecord::Type::Binary::Data object instead of a String when a prepared statement is used.

Initial thought is to propagate the info about prepared statement from the query.  I am thinking there should be a way to detect if the result is escaped, but I haven't found any way to do that.

Also, I have to make sure that the data is actually stored the same way in the DB regardless of wether prepared statements are used.

**Comment by kares** [comment]
hmm, these were working fine at some point < 4.2 ... must be something about the "new" AR::Type-system internals ;( ?

if other adapters are doing PSs fine it would be best to not mess with RubyJdbcConnection's API much ... it's used at least for a few projects (the "native" Java parts as well - that is why we need to be careful there)

isn't that a driver bug that the result differs depending on PS ?

**Comment by donv** [comment]
I'm starting to look for another solution now.  Just good to know what the problem is :)

**Comment by kares** [comment]
noticed as was curious why it's taking so long for my build to finish :) ... the new commits look much better to me - hopefully it will end-up stable in the long term otherwise we should resort to PG's AR::type patching.

**Comment by donv** [comment]
One discovery I'd like confirmation on:  It looks like the binary content is stored as a hex escaped string when **NOT** using prepared statements.  That means the content is not stored as it is, but converted to a hex string with twice the size.  I think THAT is the problem, not the other way around.

So I think the fix should be to ensure the data is stored correctly, and then we should never have to unescape when reading from the database.
