### ISSUE TITLE
Connection to PostgreSQL with Unix domain socket

### ISSUE THREAD

**Issue by pmontrasio** [jruby/activerecord-jdbc-adapter#677]
I'm trying to move a Rails 4.2 project from MRI to JRuby. The warning

    NOTE: ActiveRecord 4.2 is not (yet) fully supported by AR-JDBC, please help us finish 4.2 support - check http://bit.ly/jruby-42 for starters

is not particularly inviting but if it passes the tests it would be OK. The show stopper so far is that I can't connect to my database over a Unix domain socket. I tried several configurations of database.yml but none of them worked. I googled around and maybe JDBC can connect to databases only over TCP. If that's not the case, can anybody provide an example of a database.yml that connects to the Unix domain socket? Thanks.

**Comment by kares** [comment]
standard Java does not support Unix sockets directly, that is why JRuby kind of invents them with an external library. most JDBC drivers usually provide 1st class support for connecting without any native dependencies (outside JRE) ... this is also the case with Postgre's jdbc-postgres driver we're using.

**Comment by pmontrasio** [comment]
Thanks @kares for the prompt reply. The way I understood your answer is that the driver supports the Unix domain socket but at https://jdbc.postgresql.org/documentation/93/prepare.html I read

    Because Java does not support using unix sockets the PostgreSQL™
    server must be configured to allow TCP/IP connections

so I could have understood you wrong.
So, no way to connect to a Unix domain socket?

**Comment by archenroot** [comment]
@pmontrasio something is here:
https://github.com/impossibl/pgjdbc-ng/issues/169
