### ISSUE TITLE
activerecord-jdbcpostgresql-adapter: undefined method `transaction_status'

### ISSUE THREAD

**Issue by bbraga** [jruby/activerecord-jdbc-adapter#686]
I am using the Que gem for my job_queue on rails and when I issue a destroy for the job I get the following:
```
NoMethodError: undefined method `transaction_status' for #<ActiveRecord::ConnectionAdapters::PostgreSQLJdbcConnection:0x7f816b87>
```
I debugged a bit and was able to pinpoint that this call and perhaps others have not made it to this adapter yet - note the [Que gem](https://github.com/chanks/que) is compatible with jqruby-pg and with the pg adapter as well.

Here is a possible implementation
[Transaction Status](https://github.com/headius/jruby-pg/search?utf8=%E2%9C%93&q=transaction_status) as implemented on jruby-pg

**Comment by kares** [comment]
we generally do not implement APIs offered by C drivers such as **pg** or **mysql2** ... our purpose is AR compatibility using 'standard' JDBC APIs. if its simple enough to do I'll try to add `transaction_status`, but if you have gems that rely on pg internals you're better off with jruby-pg.

**Comment by kares** [comment]
here's a [failed attempt](https://github.com/kares/activerecord-jdbc-adapter/commit/4d6e0e0c52d12b0166810dffc9f898141a23bee6) - seems not passing the test as MRI. 
due limited resources, I recommend you look into it on your own as this is smt extra.
