### ISSUE TITLE
emulate_booleans is not working?

### ISSUE THREAD

**Issue by ismith** [jruby/activerecord-jdbc-adapter#687]
I'm having some trouble with emulate_booleans; I have a legacy database with tinyint(1) columns that I'd like to be treated as integers instead of as booleans.  `ActiveRecord::ConnectionAdapters::MysqlAdapter.emulate_booleans = false` doesn't seem to be doing the trick.

I've created a repro case in a rails app of 4 commits (https://github.com/ismith/emulate_booleans); its schema contains a table with a single tinyint(1) column, and 3 values (0, 1, 2).

To set it up locally: `rake db:create db:structure:load`.

Now, in rails console, using jruby-1.7.20:
```
jruby-1.7.20 :001 > ArJdbc::MySQL.emulate_booleans # as expected
 => false 
jruby-1.7.20 :002 > ActiveRecord::Base.connection.execute("SELECT * from my_table")
   (4.0ms)  SELECT * from my_table
 => [{"my_tinyint"=>0}, {"my_tinyint"=>1}, {"my_tinyint"=>1}] 
jruby-1.7.20 :003 > 
```

Compare with ruby-2.2.2 (using the activerecord-mysql-adapter):
```
2.2.2 :001 > ActiveRecord::Base.connection.execute("SELECT * from my_table").to_a
  skip_logging (0.1ms)  SET SQL_AUTO_IS_NULL=0
  skip_logging (0.1ms)  SET SQL_MODE='STRICT_ALL_TABLES'
   (0.2ms)  SELECT * from my_table
 => [["0"], ["1"], ["2"]] 
2.2.2 :002 > 
```

Any thoughts on what this might be?  I took a look through this project's issues, and only found closed issues suggesting that emulate_booleans should work.

(Oh, and this is with activerecord-jdbc-adapter 1.3.18, jdbc-mysql 5.1.36, activerecord 4.2.)

**Comment by kares** [comment]
thanks, we do have a test-case covering that feature - not sure what's going on there ... will have to look.
from the results it seems you expect `execute` to behave the same with AR-JDBC as with AR+whatever the C-driver is - its usually never the case and usually we do not care about such low level APIs, but if its fixable ... although if I recall mysql2 gem returns native DB objects there (that seem like arrays).

**Comment by ismith** [comment]
Sorry for the ambiguity - I'm definitely not expecting identical results from the two adapters.  The salient detail is that the data returned is different - 0, 1, 1 instead of 0, 1, 2.  (See db/structure.sql in the linked repo, and I confirmed with mysql that the values in the db are 0, 1, and 2.

**Comment by kares** [comment]
I see now - got confused the first time, interestingly `tinyint(1)` comes back on the JDBC end as type BIT not TINYINT ... not sure changing the handling for BIT will not break anyone else ;(

**Comment by kares** [comment]
try my fork for the time being as I need to figure out smt else before I push the .jar here onto **1-3-stable**

**Comment by ismith** [comment]
`rake build` suceeds, but I can't install the resuting gem - Maven complains "Unknown lifecycle phase "[]="".  Full gem_make.out here: https://gist.github.com/ismith/953d408fea1a6e202dfe

**Comment by ismith** [comment]
Er, my mistake - was attempting to build master, not 1-3-stable.

**Comment by ismith** [comment]
Your fork behaves as expected in my repro app.

**Comment by ismith** [comment]
Can you elaborate on the concern about this breaking behavior for others?  I thought this behavior (returning tinyint as boolean or int) is what emulate_booleans is there for.
