### ISSUE TITLE
Model.create! returns model with nil ID

### ISSUE THREAD

**Issue by hathawad** [jruby/activerecord-jdbc-adapter#690]
I have a production Rails 3.2.22 JRuby app that uses activerecord-jdbcpostgresql-adapter version '1.2.9'.  
Recently though, I've tried to upgrade to 1.3.19 for some bug fixes (namely .pluck support).  However, it seems that a trivial Rails 3.2.22 app is broken with any version of activerecord-jdbcpostgresql-adapter  1.3.0+.  

Any Model.create calls return a model/object with a nil ID rather than the new ID (aka primary key). 
I've created a bare bones rails app to demonstrate this:
https://github.com/jrl08d/jruby_test

**To reproduce:**
* Check out app, bundle, create db's, etc
* rails c (development or production)
* Payment.create

The model that gets returned has a nil ID (which makes it more or less useless).

```log
Loading production environment (Rails 3.2.22)
irb(main):001:0> Payment.create!
  ←[1m←[36mSQL (16.0ms)←[0m  ←[1mINSERT INTO "payments" ("amount", "created_at","notes", "updated_at") VALUES (NULL, '2015-11-18 22:21:59.000000', NULL, '2015-
11-18 22:21:59.000000')←[0m
=> #<Payment id: nil, amount: nil, notes: nil, created_at: "2015-11-18 22:21:59", updated_at: "2015-11-18 22:21:59">
```

**Environment:**
```log
jruby 1.7.22 (1.9.3p551) 2015-08-20 c28f492 on Java HotSpot(TM) 64-Bit Server VM 1.8.0_65-b17 +jit [Windows Server 2008 R2-amd64]

**Comment by hathawad** [comment]
Should I chalk this up to no Rails 3.2 support?

**Comment by hathawad** [comment]
This is not an issue on Rails 4.0 
I suppose the world has moved on from Rails 3.2

**Comment by kares** [comment]
3.2 should be still working - just did no have the time to look into it yet

**Comment by hathawad** [comment]
Fair enough, I'll test any PR if you need.

**Comment by kares** [comment]
actually a small isolated test-case or piece of .rb script with everything in 1 place would help fix this sooner.

**Comment by kares** [comment]
tried a script as well as your repo - all seems well, you should upgrade your JRuby 1.7.x version : 
```
Loading production environment (Rails 3.2.20)
jruby-1.7.24 :001 > Payment.create!
  SQL (2.0ms)  INSERT INTO "payments" ("amount", "created_at", "notes", "updated_at") VALUES (NULL, '2016-03-04 12:10:13.820000', NULL, '2016-03-04 12:10:13.820000') RETURNING "id"
 => #<Payment id: 1, amount: nil, notes: nil, created_at: "2016-03-04 12:10:13", updated_at: "2016-03-04 12:10:13"> 
```
