### ISSUE TITLE
[Question] Is activerecord `4.2+` supported? 

### ISSUE THREAD

**Issue by vjdhama** [jruby/activerecord-jdbc-adapter#692]
The [activerecord-postgis-adapter](https://github.com/rgeo/activerecord-postgis-adapter) project states [here](https://github.com/rgeo/activerecord-postgis-adapter#version-3x-supports-activerecord-42) that `AR-JDBC not supporting 4.2 yet.` Is that statement still valid?

**Comment by donv** [comment]
Hi @vjdhama !

This project, activerecord-jdbc-adapter, definitely supports ActiveRecord 4.2.

**Comment by kares** [comment]
... at least to the extent we test - might be far from 100% - pls try to use the mailing list or IRC for Qs
