### ISSUE TITLE
jdbc postgresql ERROR NoMethodError: undefined method `get_oid_type' for Sinatra Active record application

### ISSUE THREAD

**Issue by bbiglari** [jruby/activerecord-jdbc-adapter#701]
I am moving my Ruby Sinatra application  to JRuby Sinatra application. I am using jdbc postgresql adapter; however, I am getting the error get_oid_type undefined method. 

I am not sure what is the reason, since I have all the setting in place. 

I have a lot of details about the issue in http://stackoverflow.com/questions/34551841/jruby-jdbc-setup-for-rake-dbmigrate-task.

Any idea??

**Comment by kares** [comment]
as noted this is application specific issue - for sinatra-activerecord the issue is its loading AR support only (not accounting for AR-JDBC). I just tested it and by loading AR-JDBC before loading the gem works ...
