### ISSUE TITLE
[Oracle] NOTE: ActiveRecord 4.2 with adapter: oracle is not (yet) fully supported by AR-JDBC, please consider helping us out.

### ISSUE THREAD

**Issue by jkuchta** [jruby/activerecord-jdbc-adapter#707]
Hi,

I am running 1.3.19 with Rails 4.2 and receive this notice when starting my app:
`NOTE: ActiveRecord 4.2 with adapter: oracle is not (yet) fully supported by AR-JDBC, please consider helping us out.`

Where can I find the list of issues needed for Oracle support?

**Comment by kares** [comment]
@jkuchta you should probably try running the test suite against Oracle. I believe I left some failures behind.

**Comment by jkuchta** [comment]
@kares running into a little issue getting the tests up and running. I read the guide but am receiving the following:

`rake appraisal:rails42 test_oracle TEST=test/db/oracle/rake_test.rb`

`LoadError: no such file to load -- arjdbc/jdbc/adapter_java`

**Comment by kares** [comment]
we're trying to [refactor master](https://github.com/jruby/activerecord-jdbc-adapter/issues/572) - not to have to commit the ext.jar (so you need to build it `rake jar`) - on [1-3-stable](https://github.com/jruby/activerecord-jdbc-adapter/tree/1-3-stable) the .jar is still part of the repo - updated when changes to the native parts are made (under src/).

**Comment by jkuchta** [comment]
@kares Thanks, I have the tests running using `rake appraisal:rails42 test_oracle`

I am seeing this output: 
`173 tests, 83 assertions, 6 failures, 134 errors, 0 pendings, 1 omissions, 0 notifications`

It looks like most of the errors are table or view does not exist, similar to the following. Are these errors expected and only the failures are an issue?
`ActiveRecord::StatementInvalid: ActiveRecord::JDBCError: java.sql.SQLSyntaxErrorException: ORA-00942: table or view does not exist
  : DROP TABLE "USERS"` 

Also, using the rails32 appraisal gives similar results:
`170 tests, 86 assertions, 7 failures, 125 errors, 0 pendings, 0 omissions, 0 notifications`

**Comment by kares** [comment]
likely :hankey:  test behaviour on Oracle ... there should not be that many failures - but I've seen it as well.
usually happens when there's a failure that is not well isolated and affects other tests (or there's smt wrong around test lifecycle setup/teardown). I'm sure you'll figure these out as you look into them.

**Comment by kares** [comment]
closing as there's been no further feedback and issue is very generix at this point.
