### ISSUE TITLE
Not compatible with Bundler 1.12

### ISSUE THREAD

**Issue by angryzor** [jruby/activerecord-jdbc-adapter#724]
Something changed in the 1.12 release of Bundler that changes the priority of requires (or at least that's what it looks like).

Since I updated bundler ActiveRecord no longer [requires](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_adapters/connection_specification.rb#L172) the [AR-JDBC connection adapters](https://github.com/jruby/activerecord-jdbc-adapter/blob/master/lib/active_record/connection_adapters/postgresql_adapter.rb), instead preferring to use its [own builtin adapter](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb), which tries to load the standard pg gem, resulting in the following error message when I attempt to `bundle exec rake db:migrate`:

```
Gem::LoadError: Specified 'postgresql' for database adapter, but the gem is not loaded. Add `gem 'pg'` to your Gemfile (and ensure its version is at the minimum required by ActiveRecord).
Gem::LoadError: pg is not part of the bundle. Add it to Gemfile.
```

Switching back to Bundler 1.11.2 resolves the problem.
I'm using Sinatra with the `sinatra-activerecord` gem, using the `activerecord-jdbcpostgresql-adapter` helper gem as database adapter.

Gemfile:

``` ruby
source 'https://rubygems.org'

gem 'config'

gem 'grape'
gem 'sinatra'

gem 'pg', platform: :ruby
gem 'activerecord-jdbcpostgresql-adapter', platform: :jruby
gem 'activerecord'
gem 'sinatra-activerecord'

gem 'rsolr'
gem 'nokogiri'

gem 'sinatra-asset-pipeline'
gem 'sinatra-flash'
gem 'autoprefixer-rails'
gem 'haml'

gem 'net-ldap'
gem 'warden'

gem 'i18n'

group :development do
    gem 'pry'
    gem 'ruby-graphviz', '~> 1.2.2'

    gem 'neo4j-core'
    gem 'neography'
end

group :production do
    gem 'puma'
end
```
##

**Comment by jaimerson** [comment]
Same here, using `mysql`. See [before](https://travis-ci.org/killbill/killbill-admin-ui/builds/126564968) and [after](https://travis-ci.org/killbill/killbill-admin-ui/builds/127197080) the downgrade.

**Comment by kares** [comment]
for now master is WiP (pretty much on hold due limited resources) ... has regressions compared to 1.3.x. 
also if someone could please confirm if `branch: '1-3-stable'` works with 1.12.5
