### ISSUE TITLE
[db2] serialize with custom class does not work

### ISSUE THREAD

**Issue by rsov** [jruby/activerecord-jdbc-adapter#725]
Active Record - 4.2
ArJdbc - 1.3.20
JRuby - 9.1.0.0
Database - DB2/As400

This worked on AR-3.2

Ran into an issue where return value from `CustomDateSerialize#dump(value)` does not get written to database

Purpose of it is to turn a Date class into an integer (YYYYMMDD)

``` ruby
class CustomDateSerialize

  def self.dump(value)
    puts 'this shows up, so the method does gets called'

    if value.respond_to? 'strftime'
      value.strftime('%Y%0m%0d').to_i
    else
      value
    end
  end

  def self.load(value)
    Date.strptime(value.to_s, '%Y%m%d') rescue nil
  end

end
```

Expected result: 
`Date.new(2016, 1, 1) -> 20160101`

Gotten:
`Date.new(2016, 1, 1) -> 2016-01-01` (Default date.to_s)
##

**Comment by kares** [comment]
yes - unfortunately DB2 adapter is hard to support ... esp. AS400 (do not have access to such machine). 
AR 4.2 integration simply needs more work. there's also an attempt to get it out [into a standalone gem](https://github.com/pierrickrouxel/activerecord-jdbcas400-adapter).

**Comment by rsov** [comment]
That makes sense. We unfortunately have an as400. How is the AR 5 integration for it looking? 

If we figure it out, will submit a pull request

**Comment by kares** [comment]
there's some progress on a branch but needs more work.
not sure if someone will popup or sponsor the Rails 5 integration. we're somehow quite low on help on this front.
