### ISSUE TITLE
The previously-deprecated -i switch to pg_dump is no longer supported in PostgreSQL 9.5.

### ISSUE THREAD

**Issue by evilrich** [jruby/activerecord-jdbc-adapter#729]
`rake db:structure:dump` from a Rails 3 app fails with

> pg_dump: invalid option -- i

This is used in lib/arjdbc/tasks/databases3.rake line 115 (version 1.3.20).

This switch was deprecated in PostgreSQL 8.4 and was finally removed in 9.5.
##

**Comment by mortonar** [comment]
#783 Should fix this(barring anything I'm missing).

**Comment by kares** [comment]
resolved at https://github.com/jruby/activerecord-jdbc-adapter/pull/783
