### ISSUE TITLE
id=0 always being returned for create record jRuby and Derby adapter

### ISSUE THREAD

**Issue by coraxcyber** [jruby/activerecord-jdbc-adapter#737]
We are generating a new record using jRuby and activerecord using your Derby DB adapter. Every time we use the .create method on a model (in this test case, Person), the corresponding object that is created always has an ID of 0. However, the record created in our database is auto incremented successfully and the correct primary key ID value is being assigned.
# <Person id: 0, name: "FRED1">
# <Person id: 0, name: "FRED2">
# <Person id: 0, name: "FRED3">
# <Person id: 0, name: "FRED4">

etc...

We are really stuck with this issue and cannot complete a major project without this functionality. Any help you can offer regarding this issue would be very much appreciated!
##

**Comment by kares** [comment]
thanks. you did not provide a lot of information. I'd be happy to look into your app (if you're into [that](http://kares.org/#contact)).

**Comment by coraxcyber** [comment]
Hey sorry, the output seems to have been removed from my post!

As there are several components to discuss, would you be able to do a screen share at some point that is convenient for you?

**Comment by kares** [comment]
yes but please contact me privately but no pushing. you could also provide more info here and maybe somebody will pick it up. the tricky part should be reproducing in isolation.

**Comment by coraxcyber** [comment]
Sure, I will follow up with a write up and more detail shortly.

**Comment by kares** [comment]
at this point the issue has no relevant details: trace info and/or a way to reproduce.
will likely get closed as invalid and we'll be hoping for another user report or declare the bug env specific.
