### ISSUE TITLE
'activerecord-jdbcderby-adapter' not compatible with ActiveRecord 5

### ISSUE THREAD

**Issue by amudgal** [jruby/activerecord-jdbc-adapter#750]
I had to downgrade my rails version to 4 in order to make the active record-jdbcderby-adapter to work. Do we know when it would be compatible 
##

**Comment by kares** [comment]
... probably when someone decides to make it so - we're low on maintainers and need help/support

**Comment by enebo** [comment]
It is unfortunate, but we do not have the resources to work on this adapter without someone stepping up to help maintain it for/with us.  I am resolving as WONTFIX :(

If someone does want to help out then we will try and lend our expertise and enthusiasm for the effort.
