### ISSUE TITLE
There was an error while trying to load the gem 'activerecord-jdbcsqlite3-adapter'.

### ISSUE THREAD

**Issue by anta40** [jruby/activerecord-jdbc-adapter#776]
Steps to reproduce (OS is 32-bit Windows 10):
1. Get the latest JRuby (9.1.7.0). Extract to C:\jruby. Put C:\jruby\bin in %PATH%.
2. Install the latest Rails: `gem install rails -v 5.0.1`
3. Install the latest activerecord-jdbcsqlite3-adapter: `gem install activerecord-jdbcsqlite3-adapter -v 1.3.22`
4. Install the latest Trinidad: `gem install trinidad -v 1.5.0.B2` 
5. Create a test app, e.g `rails new pertamaxx`
6. cd into it, and ran `jruby -S trinidad`

Error log attached:
[ar.txt](https://github.com/jruby/activerecord-jdbc-adapter/files/747836/ar.txt)
> An exception happened during JRuby-Rack startup
> There was an error while trying to load the gem 'activerecord-jdbcsqlite3-adapter'.
> Gem Load Error is: uninitialized constant ActiveRecord::ConnectionAdapters::Column::Format

**Comment by kares** [comment]
AR-JDBC does not (yet) support AR 5.0 .. although there's some effort for sqlite3 support with a [pre-relase](https://rubygems.org/gems/activerecord-jdbcsqlite3-adapter/versions/5.0.pre1)

**Comment by kares** [comment]
actually if you look around there's already the same error reported at: https://github.com/jruby/activerecord-jdbc-adapter/issues/747 closingas duplicate
