### ISSUE TITLE
Rails 4.2 Oracle Warning Notice

### ISSUE THREAD

**Issue by jkuchta** [jruby/activerecord-jdbc-adapter#777]
Is there a list of open issue for Oracle and Rails 4.2?

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/41909108-rails-4-2-oracle-warning-notice?utm_campaign=plugin&utm_content=tracker%2F136963&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F136963&utm_medium=issues&utm_source=github).

**Comment by kares** [comment]
well, you could run the test-suite and also AR's suite and see how well it goes, there's no list maintained.
due the limited time spent I really did not feel like I did a good job for Oracle when implementing 4.2 support.

**Comment by enebo** [comment]
Rails 4.2 is many versions behind current Rails and we are not supporting Oracle (at least atm) in Rails 5+).
