### ISSUE TITLE
5.0.pre1 release not tagged in git

### ISSUE THREAD

**Issue by jrochkind** [jruby/activerecord-jdbc-adapter#782]
There is a `5.0.pre1` released to rubygems, but there is no corresponding git tag. 

There are git tags for previous releases. 

Git tags make it possible/easier to figure out what version of the repo corresponds to what rubygems release, to see changes between versions, often useful for debugging too. 

Please make it a rule to tag releases in git when releasing to rubygems?

**Comment by headius** [comment]
Sorry about that! We did this release very quickly before a conference and had unpushed bits locally. I've sorted it out, generally, but the history is a little mucked up.
