### ISSUE TITLE
Rails 5.1 changed ActiveRecord::StatementInvalid initialize params

### ISSUE THREAD

**Issue by lardcanoe** [jruby/activerecord-jdbc-adapter#785]
Because of https://github.com/rails/rails/commit/bc6c5df4699d3f6b4a61dd12328f9e0f1bd6cf46 the params for https://github.com/jruby/activerecord-jdbc-adapter/blame/332d8ef6ea0839a6d24401009056a1c2154c0b0a/lib/arjdbc/mysql/adapter.rb#L868 are now changed.

Just a heads up in case the rails-5 branch gets some love.

Thanks!

**Comment by yahonda** [comment]
I think this issue has been addressed by 57cdf0b7c35c72cde59594bed8991b6c639f41c7 which removes ` translate_exception` method from `ArJdbc::MySQL` module.

**Comment by enebo** [comment]
Speculative closing since 51.0 is out and this was changed before then.
