### ISSUE TITLE
MS Sql with Ruby on Rails 5.1

### ISSUE THREAD

**Issue by bilalahmed144** [jruby/activerecord-jdbc-adapter#788]
hello friend:
i want connect MS SQL(online db) to my ruby on rails app and i only want to show data from sql to ruby on rails(v 5.1) app.
Please help me
i have MS SQL Database ip,username, password and db name,
now what i do please give solution step by step guide please...
and i used three gems:
gem 'activerecord-sqlserver-adapter'
gem 'tiny_tds', '~> 0.7.0'
gem 'ruby-odbc'

i want full database result show in my ruby on rails app(not update or insert or delete only select function want).

but some error show on when start that server with (rails s command) show in picture...
![screenshot from 2017-05-12 16-36-44](https://cloud.githubusercontent.com/assets/28337547/25997405/47a6d1ae-3735-11e7-9237-0f86bb23322b.png)

**Comment by kares** [comment]
please make sure you understand what you're using, while AR-JDBC supports MS-SQL (not AR 5.x ATM)
you're using `gem 'activerecord-sqlserver-adapter'` which is a completely different gem, you should check-out their home page and likely try updating to latest version (2.3.8 might not support AR 5.x)

**Comment by bilalahmed144** [comment]
i m also used latest version .
