### ISSUE TITLE
Rails 5 PostgreSQL remove_index produces invalid SQL.

### ISSUE THREAD

**Issue by Mihail-K** [jruby/activerecord-jdbc-adapter#796]
Currently on the `rails-5` branch, migrations using `remove_index` will fail because invalid SQL is produced.

For example,
```ruby
remove_index :users, :created_at
```
Produces:
```sql
DROP INDEX "index_users_on_created_at" ON "users";
```

But Postgres doesn't accept an `ON` clause as part of `DROP INDEX`.
See: https://www.postgresql.org/docs/9.6/static/sql-dropindex.html

The correct output should just be:
```sql
DROP INDEX "index_users_on_created_at";
```

**Comment by rdubya** [comment]
This should be addressed with the 50 release. Please reopen if we have missed something.
