### ISSUE TITLE
Rails 5.0 support check list/notes

### ISSUE THREAD

**Issue by enebo** [jruby/activerecord-jdbc-adapter#824]
This is a list of activities we need to release 5.0 support.  At this point we have some individual issues that likely will not be fixed at release time.

- [x] Add 1 issue per problem for big three adapters (mysql, sqlite, postgresql)
- [x] Make master a maintenance branch and move rails-5 to master
- [x] Fixup build script to generate .gem (probably mostly working now)
- [x] Add to travis (not technically needed for release but highly desirable)
- [x] pare down local test suite to only test things not covered by AR test suite

**Comment by rsov** [comment]
Has DB2 / AS400 support been dropped for rails 5?
