### ISSUE TITLE
Find proper namespace for MySQL::Error

### ISSUE THREAD

**Issue by enebo** [jruby/activerecord-jdbc-adapter#834]
Right now this is ::MySQL2::Error and I just remembered I forgot to figure this out but it is RELEASE TIME.  So we will correct this for next release.

**Comment by kares** [comment]
moved this out - we never mocked these and it isn't a good idea to do so (unless there's a **mysql2** gem API)
it was only needed due some tests - mostly some mocked Rails MySQL rake task ones - so its now loaded for those. reference commit: https://github.com/jruby/activerecord-jdbc-adapter/commit/a72eeedd7d64349eaf262d3c30066cf09d39f1a8
