### ISSUE TITLE
rake rails:db:* task get NameError: uninitialized constant ARTest

### ISSUE THREAD

**Issue by yahonda** [jruby/activerecord-jdbc-adapter#856]
#### Steps to reproduce:
```ruby
$ cd activerecord-jdbc-adapter
$ rake rails:db:mysql:rebuild
Resolving dependencies....
rake aborted!
NameError: uninitialized constant ARTest
Did you mean?  TARGETS
/home/yahonda/git/activerecord-jdbc-adapter/rakelib/rails.rake:101:in `block in (root)'
Tasks: TOP => rails:db:mysql:rebuild => rails:db:mysql:drop
(See full trace by running task with --trace)
$
````

This `NameError: uninitialized constant ARTest` reproduces with all of these rake tasks.
```ruby
$ rake -T |grep 'rails:db'
rake rails:db:mysql:build         # Build the MySQL test databases
rake rails:db:mysql:drop          # Drop the MySQL test databases
rake rails:db:mysql:rebuild       # Rebuild the MySQL test databases
rake rails:db:postgresql:build    # Build the PostgreSQL test databases
rake rails:db:postgresql:drop     # Drop the PostgreSQL test databases
rake rails:db:postgresql:rebuild  # Rebuild the PostgreSQL test databases
$


#### Environment:
```ruby
$ ruby -v
jruby 9.1.14.0 (2.3.3) 2017-11-08 2176f24 Java HotSpot(TM) 64-Bit Server VM 25.151-b12 on 1.8.0_151-b12 +jit [linux-x86_64]
activerecord-jdbc-adapter master branch
```

Based on this commit https://github.com/rails/rails/commit/499dec0102a30eab566ff3e58ff7148a0868cc6c
It looks like `ARTest` module is defined in this file https://github.com/rails/rails/blob/5-1-stable/activerecord/test/support/config.rb .

**Comment by kares** [comment]
seems unfortunate - not sure how to help out without looking down into the setup.
would be nice to have these helpers working but maybe you're the first to really attempt to use them ...

**Comment by enebo** [comment]
Is this fallout from cloning part of AR rake tasks to our testsuite?  Why would that type not load for us?

**Comment by kares** [comment]
we're no longer using the Rails provided rake tasks - so this is invalid for the moment.
for now, reinventing **rails:test_mysql** asn others seems as a better option ... less problematic so far.
we do miss the ability to setup Rails test database, but that wasn't the topic here ...
