### ISSUE TITLE
PostgreSQL Array type exposed in _before_type_cast

### ISSUE THREAD

**Issue by aschmied** [jruby/activerecord-jdbc-adapter#864]
The type of the `_before_type_cast` value of a PosgreSQL array-valued attribute on an ActiveRecord model is `ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Array::Data` after a save. This is a behaviour change since Rails/AR 4. We noticed it because we have a validation for array-valued fields that asserts that `attribute_before_type_cast.instance_of? [].class`. The validation fails after this change.

# Environment

* JRuby 9.1.14.0
* Windows 10

# Reproduction

We have a `Waveform` model with a PostgreSQL array-valued attribute `samples`.

## Rails 4 Behaviour

Rails 4.2.7.1
ActiveRecord 4.2.7.1
activerecord-jdbc-adapter 1.3.24

    > rails c test
    irb(main):001:0> w = Waveform.new
    irb(main):006:0> w.samples = [1,2,3]
    irb(main):009:0> w.save
    irb(main):012:0> w.samples_before_type_cast.class
    => Array

## Rails 5 Behaviour

Rails 5.0.6
ActiveRecord 5.0.6
activerecord-jdbc-adapter branch 50-stable revision 5110ec0446150fa37dcf2d2902d241dec55c91c9

    > rails c test
    irb(main):001:0> w = Waveform.new
    irb(main):006:0> w.samples = [1,2,3]
    irb(main):009:0> w.save
    irb(main):013:0> w.samples_before_type_cast.class
    => ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Array::Data

**Comment by aschmied** [comment]
@rdubya you are correct. This happens using MRI ruby with the "pg" Gem. Do you know whether this behaviour was intended? If not I'll open an AR issue

**Comment by rdubya** [comment]
I believe they reworked a decent amount of the type casting stuff, so I'm guessing its expected to work that way. Feel free to open a ticket with the AR team though. I'll close this one for now.
