### ISSUE TITLE
Rails 5.1.5 postgres adapter throws NameError

### ISSUE THREAD

**Issue by michaeldbarry** [jruby/activerecord-jdbc-adapter#867]
Using activerecord-jdbcpostgresql-adapter 50.0 with @rdubya patches from [3ad4910](https://github.com/jruby/activerecord-jdbc-adapter/commit/3ad4910a5c065f73e49bca074e5ac4a05978a4c9]) throws the following error:

> NameError: undefined local variable or method `max_identifier_length' for #<ActiveRecord::ConnectionAdapters::PostgreSQLAdapter

adding

alias_method :max_identifier_length, :table_alias_length

to lib/arjdbc/postgresql/adapter.rb fixes the issue.

versions:
```
rails 5.1.5
activerecord (5.1.5)
      activemodel (= 5.1.5)
      activesupport (= 5.1.5)
      arel (~> 8.0)
activerecord-jdbc-adapter (50.0)
      activerecord (>= 2.2)
activerecord-jdbcpostgresql-adapter (50.0)
      activerecord-jdbc-adapter (~> 50.0)
      jdbc-postgres (>= 9.4, < 43)
```

**Comment by rdubya** [comment]
Thanks for the info. I should be able to get this taken care of for the 51 release

**Comment by rdubya** [comment]
Confirmed that this should be taken care of when 51 is released.

**Comment by pat** [comment]
I've just come across this error [using Rails 5.0.7, which was released a week ago](https://travis-ci.org/pat/thinking-sphinx/jobs/362945270) (see the last test run - Appraisal's going through 3.2 -> 5.0).

Rails 5.0.6 is fine - so I guess if there's a fix for this coming in 51.0, perhaps a 50.1 release is needed as well? :|

**Comment by meetme2meat** [comment]
@rdubya @enebo I'm still getting the above issue on master (`17e31dea362f`) branch.

**Comment by enebo** [comment]
@meetme2meat could you provide a stack trace.  Amazingly, I see postgres adapter has 2 defs of max_identifier_length.  I am wondering where it is calling and not finding it.  (If you are not getting a nice backtrace from this you can set JRUBY_OPTS="-d -Xbacktrace.style=raw" to get lots o backtraces).

**Comment by meetme2meat** [comment]
@enebo To my reckoning, it seems that `max_identifier_length` is an instance method of [PostgresAdapter](https://github.com/rails/rails/blob/5-1-stable/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb#L368-L369)

This look completed different over [here](https://github.com/jruby/activerecord-jdbc-adapter/blob/master/lib/arjdbc/postgresql/adapter.rb#L293) 

Constant like `NATIVE_DATABASE_TYPES` , method `native_database_types` and few other methods are define inside the `PostgreSQLAdapter` unlike `activerecord-jdbc-adapter` where they fall under `Postgres` module

I'm not sure that how it suppose to be here.. But redefining the `max_identifier_length` inside the `PostgreSQLAdapter` resolve the above error.

**Comment by meetme2meat** [comment]
@gellaho Can you try this
``` 
gem 'rails' ,'~ 5.1.6'
gem 'activerecord-jdbc-adapter',  github: 'jruby/activerecord-jdbc-adapter'
gem 'activerecord-jdbcpostgresql-adapter', github: 'jruby/activerecord-jdbc-adapter', platform: :jruby
```

I do not remember what action of mine stopped(this was one of the things I tried) that error but I'm not getting those error more.

**Comment by gellaho** [comment]
@meetme2meat That made the migration work.  I also had to end up installing `ant` on machine.

Is this an issue that needs to be fixed or is it expected behavior?  If it's expected, it should probably be written somewhere.
