### ISSUE TITLE
ArgumentError (wrong number of arguments (4 for 3)) using JDBC

### ISSUE THREAD

**Issue by dgpokl** [jruby/activerecord-jdbc-adapter#955]
### Summary
I am using JDBC to connect to an AS/400 database and I'm seeing a fatal error as soon as I define a model and call `establish_connection`. The error is raised at `lib/arjdbc/abstract/core.rb:12` which seem to be related to the 4 vs 3 argument constructors on database adapters.

As you can see in the stacktrace below:
[lib/arjdbc/jdbc/connection_methods.rb:8](https://github.com/jruby/activerecord-jdbc-adapter/blob/master/lib/arjdbc/jdbc/connection_methods.rb#L8) calls the adapter's constructor using 4 arguments.
[lib/arjdbc/jdbc/callbacks.rb:12](https://github.com/jruby/activerecord-jdbc-adapter/blob/master/lib/arjdbc/jdbc/callbacks.rb#L12) calls `super` **without arguments,** passing the 4 arguments through to...
[lib/arjdbc/abstract/core.rb:12](https://github.com/jruby/activerecord-jdbc-adapter/blob/master/lib/arjdbc/abstract/core.rb#L10) which has a 3-argument constructor. Thus I get the error message:
`ArgumentError (wrong number of arguments (4 for 3))`

I read with interest the comments on (especially) #896, on #891, and on the last 2 commits [here](https://github.com/jruby/activerecord-jdbc-adapter/commits/master/lib/arjdbc/jdbc/connection_methods.rb) and it seems like the goal now is to only use 4-argument constructors throughout? So if that's true, **don't the adapters defined in this gem need to be updated accordingly, including this one?** Or (and I acknowledge this is a very real possibility) am I just using it wrong? Or is this fixed in master, which I haven't yet gotten to successfully install? Any help or guidance would be **greatly** appreciated.

To try to understand what was going on since this code in callbacks.rb is a mix-in, I made a couple quick edits to log the names of the classes involved at callbacks.rb:12 and confirmed that the current class is `ActiveRecord::ConnectionAdapters::JdbcAdapter` and the superclass it's calling super to reach is `ActiveRecord::ConnectionAdapters::AbstractAdapter`.

### Steps to reproduce
Here's a basic setup though that might suffice to demonstrate the issue. Note: I tried this leaving out steps 2-3 and it looks like you can get it to throw the same error without having the jar file even in place, so you may be able to skip them too. And it seems to me like that might mean it's not just people with super similar setups to me.
1. grab the files in this gist: https://gist.github.com/dgpokl/bc6e029f90d97c65ac3b741a548a3e7a
2. (*OPTIONAL?) Get the jt400.jar file which is in the package [here](https://sourceforge.net/projects/jt400/)
3. (*OPTIONAL?) Put it at lib/jt400.jar
4. bundle install
5. try running ruby ruby_code.rb

Expected: It should at least be able to try connecting to the DB

Actual: It throws the error seen in the stacktrace below.

### Versions, Details, etc.
* AR-JDBC's version used: **activerecord-jdbc-adapter-52.1**
 (if you've tested against master mention it): I tried, but it won't install, complains jrake not found (I'm pretty new to jruby, sorry)
* version of Rails / ActiveRecord you're running with: `activerecord 5.2.1`
* JRuby version (you might include your Java version as well) - `9.2.0.0`
* if you've setup the JDBC driver yourself please mention that (+ it's version)
I'm using a JDBC configuration exactly like this (using the jt400.jar file from the jt400 project)
```
{:adapter=>"jdbc", :driver=>"com.ibm.as400.access.AS400JDBCDriver", :url=>"jdbc:as400://10.0.0.254;naming=system;libraries=*LIBL;date format=iso;errors=full", :username=>"username", :password=>"******"}
```

include any (related) back-traces (or Java stack-traces) you've seen in the logs
```
Traceback (most recent call last):
       16: from /usr/local/bundle/gems/activerecord-5.2.1/lib/active_record/attribute_methods/primary_key.rb:75:in `primary_key'
       15: from /usr/local/bundle/gems/activerecord-5.2.1/lib/active_record/attribute_methods/primary_key.rb:87:in `reset_primary_key'
       14: from /usr/local/bundle/gems/activerecord-5.2.1/lib/active_record/attribute_methods/primary_key.rb:99:in `get_primary_key'
       13: from /usr/local/bundle/gems/activerecord-5.2.1/lib/active_record/model_schema.rb:324:in `table_exists?'
       12: from /usr/local/bundle/gems/activerecord-5.2.1/lib/active_record/connection_handling.rb:90:in `connection'
       11: from /usr/local/bundle/gems/activerecord-5.2.1/lib/active_record/connection_handling.rb:118:in `retrieve_connection'
       10: from /usr/local/bundle/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:1008:in `retrieve_connection'
        9: from /usr/local/bundle/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:380:in `connection'
        8: from /usr/local/bundle/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:521:in `checkout'
        7: from /usr/local/bundle/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:793:in `acquire_connection'
        6: from /usr/local/bundle/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:832:in `try_to_checkout_new_connection'
        5: from /usr/local/bundle/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:853:in `checkout_new_connection'
        4: from /usr/local/bundle/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:809:in `new_connection'
        3: from /usr/local/bundle/gems/activerecord-jdbc-adapter-52.1-java/lib/arjdbc/jdbc/connection_methods.rb:8:in `jdbc_connection'
        2: from /usr/local/bundle/gems/activerecord-jdbc-adapter-52.1-java/lib/arjdbc/jdbc/callbacks.rb:12:in `new'
        1: from /usr/local/bundle/gems/activerecord-jdbc-adapter-52.1-java/lib/arjdbc/abstract/core.rb:12:in `initialize'
ArgumentError (wrong number of arguments (4 for 3))
```

**Comment by kares** [comment]
unfortunately, due lack of resources, anything except MySQL, PG, SQLite3 isn't supported on AR 5.x atm
... it might work to some extend but eventually you might run into issues which you will need to iron out

**Comment by aamir-pk** [comment]
I am facing the same issue while connecting to Oracle

**Comment by kares** [comment]
hey all, I do not think this will fix. adapters except for MySQL, PostgreSQL and SQLite weren't updated.
some might work but not much testing has been done towards supporting any other adapters further ...
we simply lack resources to do so. efforts are welcome, maintenance will end up being community driven.

**Comment by headius** [comment]
I'm afraid this issue is in danger of being closed due to lack of community help.

We currently only have resources to support MySQL, PostgreSQL, and SQLite as part of our regular ARJDBC releases. We would like to be able to support all the same databases that worked in ARJDBC 1.3.x but we need community members to step up and take ownership.

@dgpokl You have done some good investigation into this... perhaps you could help us by putting together a pull request that fixes the constructors in question?

@aamir-pk For Oracle support our official recommendation is to use the oracle-enhanced adapter: https://github.com/rsim/oracle-enhanced

**Comment by headius** [comment]
I'm going to just close this and hope folks from the community can help us pick up support in the future. Please help!
