### ISSUE TITLE
Is 52.1 stable?

### ISSUE THREAD

**Issue by aschmied** [jruby/activerecord-jdbc-adapter#956]
I'm unsure whether here or the JRuby mailing list is the best place to ask this, but I'll try here since my question is specific to ar-jdbc-adapter. I'm wondering whether ar-jdbc-adapter 52 is stable. I see a 52-stable branch, but it does not appear to have been merged to master and is not mentioned in the project README. We are eager to upgrade to Rails 5.2, so I'm excited for the 52-stable release.

**Comment by rdubya** [comment]
It is considered stable for sqlite, postgres, and mysql. The other adapters have not been updated.

**Comment by enebo** [comment]
stable-50 is 50.x
stable-51 is 51.x
stable-52 is 52.x
and master is for next release.

I see our README.md note is out of date.... :|
