### ISSUE TITLE
Rails 6 support

### ISSUE THREAD

**Issue by dr-itz** [jruby/activerecord-jdbc-adapter#980]
This is to track/coordinate support for Rails 6.

/cc @enebo @kares @rdubya

**Comment by dr-itz** [comment]
So..from the remaining few test failures:

* `CoreTest#test_pretty_print_persisted`: turns out this shows up on 5x-stable too when running on JRuby 9.2.x, 9.1.x doesn't show the problem. I'll try and see if I can extract a test
* `LogSubscriberTest#test_vebose_query_logs`: cannot reproduce locally just yet...will look closer in the next few days or so
* There's a query cache problem for PG I'll look at
* Sometimes we get this, might be jruby/jruby#5519

```
Exception in thread "Ruby-0-Thread-92: /home/travis/.rvm/gems/jruby-9.2.5.0/bundler/gems/rails-da44a9c0490a/activerecord/test/cases/reaper_test.rb:73" java.lang.NullPointerException
	at org.jruby.internal.runtime.ThreadService.getMainThread(ThreadService.java:232)
	at org.jruby.RubyThread.exceptionRaised(RubyThread.java:1762)
	at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:112)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by dr-itz** [comment]
Quick update: the failing pretty print test is about a Time being off. I can make the test pass by setting `TZ=-1:00`. No idea yet if it's fixture parsing or printing. That's for tomorrow, unless someone beats me to it (hint, hint, I love date/time handling sooo much)

* Expected: `written_on: 2003-07-16 14:28:11 UTC`
* Actual: `written_on: 2003-07-16 13:28:11 UTC`
* Fixture: `written_on: 2003-07-16t15:28:11.2233+01:00`

**Comment by dr-itz** [comment]
The pretty print problem should be fixed by jruby/jruby#5583 if that was actually the only problem. Let's see how that goes.

**Comment by enebo** [comment]
@dr-itz I just restarted last arjdbc travis job after that merge which should pull in latest and greatest....

**Comment by dr-itz** [comment]
@enebo it's pinned to 9.2.5.0....the jruby-head are currently disabled. To test it out, I pushed to my branch again with two jruby-head builds: https://travis-ci.org/dr-itz/activerecord-jdbc-adapter/builds/486663038
but that did of course not work as it picked up `jruby 9.2.6.0-SNAPSHOT (2.5.3) 2019-01-30 5913dff`...three commits behind 😞 ...will restart tomorrw

**Comment by dr-itz** [comment]
@enebo so while it did pick up the correct version now it didn't help....there's still a problem with an empty zone somewhere 😞 I will debug more. I could just change Time#zone to return nil instead of an empty string, but that's just papering over the real problem. Guess I need to run with the whole Rails/AS stuff loaded, not some reduced version

**Comment by enebo** [comment]
@dr-itz I have no doubts you have improved jruby itself and if you can figure this out you will no doubt be helping us more...but I know how frustrating tracking down date issues is :)

**Comment by dr-itz** [comment]
@enebo very frustrating indeed. But I think I figured it out this time. Basically there was a `clone` hidden in there. It's a bit more intrusive than I hoped for...let's see how CI goes

**Comment by fadyZohdy** [comment]
@dr-itz @enebo we need some features from rails 6 . when can we expect official support for it ? and is current master good enough to be used ?
and thank you for the amazing work you are doing. 🙏

**Comment by enebo** [comment]
@fadyZohdy we would appreciate someone to try master with Rails 6.  We are green with a small handful of excluded tests but many of those tests are the same tests we exclude for Rails 5.2 so things should be good to go.

**Comment by dr-itz** [comment]
@fadyZohdy yes, master should be stable enough for Rails 6.0.0.beta.3 - just make sure to use it with JRuby 9.2.6.0 and keep in mind things on the Rails side have not yet settled and every new beta breaks a few things. But now worries, I keep track (more or less) and will be ready with the fixes a few days after a new beta release.

@enebo maybe we could do an official beta release? Like 60.0.beta3 to keep in sync with Rails? It would be easier for people to use and test arjdbc

**Comment by enebo** [comment]
@dr-itz we talked about doing one much closer to official release but they must be getting close.  I also plan on putting out 5x.y releases soon but I am adding some PG magic for mini_sql gem that I want all releases to have.

**Comment by kares** [comment]
Anyone following here. Thanks to Daniel(@dr-itz )'s great work & continued efforts **60.0.rc1** is now pushed.

**Comment by Confusion** [comment]
Current build failures on push requests (at least on mine) seem to be due to change in AR: 
```
Error: test: rake db:create (and db:drop)(MySQLRakeTest)
  ArgumentError: wrong number of arguments (given 2, expected 1)
/home/travis/build/jruby/activerecord-jdbc-adapter/lib/arjdbc/tasks/databases.rake:182:in `each_current_configuration'
/home/travis/.rvm/gems/jruby-9.2.7.0/bundler/gems/rails-a59b2305792d/activerecord/lib/active_record/tasks/database_tasks.rb:182:in `create_current'
/home/travis/.rvm/gems/jruby-9.2.7.0/bundler/gems/rails-a59b2305792d/activerecord/lib/active_record/railties/databases.rake:39:in `block in <main>'
/home/travis/.rvm/gems/jruby-9.2.7.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `block in execute'
/home/travis/.rvm/gems/jruby-9.2.7.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `execute'
/home/travis/.rvm/gems/jruby-9.2.7.0/gems/rake-12.3.2/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
/home/travis/.rvm/rubies/jruby-9.2.7.0/lib/ruby/stdlib/monitor.rb:226:in `mon_synchronize'
/home/travis/.rvm/gems/jruby-9.2.7.0/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
/home/travis/.rvm/gems/jruby-9.2.7.0/gems/rake-12.3.2/lib/rake/task.rb:183:in `invoke'
/home/travis/build/jruby/activerecord-jdbc-adapter/test/db/mysql/rake_test.rb:18:in `block in test: rake db:create (and db:drop)'
```

**Comment by dr-itz** [comment]
@Confusion we need to change the .travis.yml to use `AR_VERSION="6-0-stable"` instead of `AR_VERSION="master"` everywhere. Care to send a PR?

**Comment by benoittgt** [comment]
Hello

Thanks a lot for the work done. I am working on RSpec Rails next version and we have an issue with `new_column`. https://travis-ci.org/rspec/rspec-rails/jobs/577025896

Do you have any idea of what can be done? I search an open issue but didn't find any.

Here is the full stacktrace:

```
     Failure/Error: owner = CollectionOwner.new

     NoMethodError:
       undefined method `new_column' for #<ActiveRecord::ConnectionAdapters::SQLite3Adapter:0x64b73e0a>
     # /Users/bti/.rvm/gems/jruby-9.2.6.0/gems/activerecord-jdbc-adapter-50.0/lib/arjdbc/sqlite3/adapter.rb:295:in `block in columns'
     # org/jruby/RubyArray.java:2577:in `map'
     # /Users/bti/.rvm/gems/jruby-9.2.6.0/gems/activerecord-jdbc-adapter-50.0/lib/arjdbc/sqlite3/adapter.rb:282:in `columns'
     # /Users/bti/.rvm/gems/jruby-9.2.6.0/gems/activerecord-6.0.0/lib/active_record/connection_adapters/schema_cache.rb:76:in `columns'
     # /Users/bti/.rvm/gems/jruby-9.2.6.0/gems/activerecord-6.0.0/lib/active_record/connection_adapters/schema_cache.rb:82:in `columns_hash'
     # /Users/bti/.rvm/gems/jruby-9.2.6.0/gems/activerecord-6.0.0/lib/active_record/model_schema.rb:487:in `load_schema!'
     # /Users/bti/.rvm/gems/jruby-9.2.6.0/gems/activerecord-6.0.0/lib/active_record/attributes.rb:247:in `load_schema!'
     # /Users/bti/.rvm/gems/jruby-9.2.6.0/gems/activerecord-6.0.0/lib/active_record/attribute_decorators.rb:51:in `load_schema!'
     # /Users/bti/.rvm/gems/jruby-9.2.6.0/gems/activerecord-6.0.0/lib/active_record/model_schema.rb:480:in `block in load_schema'
     # /Users/bti/.rvm/rubies/jruby-9.2.6.0/lib/ruby/stdlib/monitor.rb:226:in `mon_synchronize'
     # /Users/bti/.rvm/gems/jruby-9.2.6.0/gems/activerecord-6.0.0/lib/active_record/model_schema.rb:477:in `load_schema'
     # /Users/bti/.rvm/gems/jruby-9.2.6.0/gems/activerecord-6.0.0/lib/active_record/model_schema.rb:362:in `attribute_types'
     # /Users/bti/.rvm/gems/jruby-9.2.6.0/gems/activerecord-6.0.0/lib/active_record/attribute_methods.rb:171:in `has_attribute?'
     # /Users/bti/.rvm/gems/jruby-9.2.6.0/gems/activerecord-6.0.0/lib/active_record/inheritance.rb:55:in `new'
     # ./spec/rspec/rails/matchers/has_spec.rb:26:in `block in <main>'
     # org/jruby/RubyBasicObject.java:2677:in `instance_exec'
     # /Users/bti/code/rspec-dev/repos/rspec-core/lib/rspec/core/example.rb:257:in `block in run'
     # /Users/bti/code/rspec-dev/repos/rspec-core/lib/rspec/core/example.rb:503:in `block in with_around_and_singleton_context_hooks'
     # /Users/bti/code/rspec-dev/repos/rspec-core/lib/rspec/core/example.rb:460:in `block in with_around_example_hooks'
     # /Users/bti/code/rspec-dev/repos/rspec-core/lib/rspec/core/hooks.rb:464:in `block in run'
     # /Users/bti/code/rspec-dev/repos/rspec-core/lib/rspec/core/hooks.rb:604:in `block in run_around_example_hooks_for'
     # /Users/bti/code/rspec-dev/repos/rspec-core/lib/rspec/core/example.rb:345:in `call'
     # ./lib/rspec/rails/adapters.rb:128:in `block in MinitestLifecycleAdapter'
     # org/jruby/RubyBasicObject.java:2677:in `instance_exec'
     # /Users/bti/code/rspec-dev/repos/rspec-core/lib/rspec/core/example.rb:450:in `instance_exec'
     # /Users/bti/code/rspec-dev/repos/rspec-core/lib/rspec/core/hooks.rb:373:in `execute_with'
     # /Users/bti/code/rspec-dev/repos/rspec-core/lib/rspec/core/hooks.rb:606:in `block in run_around_example_hooks_for'
     # /Users/bti/code/rspec-dev/repos/rspec-core/lib/rspec/core/example.rb:345:in `call'
     # /Users/bti/code/rspec-dev/repos/rspec-core/lib/rspec/core/hooks.rb:605:in `run_around_example_hooks_for'
     # /Users/bti/code/rspec-dev/repos/rspec-core/lib/rspec/core/hooks.rb:464:in `run'
     # /Users/bti/code/rspec-dev/repos/rspec-core/lib/rspec/core/example.rb:460:in `with_around_example_hooks'
     # /Users/bti/code/rspec-dev/repos/rspec-core/lib/rspec/core/example.rb:503:in `with_around_and_singleton_context_hooks'
     # /Users/bti/code/rspec-dev/repos/rspec-core/lib/rspec/core/example.rb:254:in `run'
     # /Users/bti/code/rspec-dev/repos/rspec-core/lib/rspec/core/example_group.rb:633:in `block in run_examples'
     # org/jruby/RubyArray.java:2577:in `map'
     # /Users/bti/code/rspec-dev/repos/rspec-core/lib/rspec/core/example_group.rb:629:in `run_examples'
     # /Users/bti/code/rspec-dev/repos/rspec-core/lib/rspec/core/example_group.rb:595:in `run'
     # /Users/bti/code/rspec-dev/repos/rspec-core/lib/rspec/core/runner.rb:121:in `block in run_specs'
     # org/jruby/RubyArray.java:2577:in `map'
     # /Users/bti/code/rspec-dev/repos/rspec-core/lib/rspec/core/runner.rb:121:in `block in run_specs'
     # /Users/bti/code/rspec-dev/repos/rspec-core/lib/rspec/core/configuration.rb:2031:in `with_suite_hooks'
     # /Users/bti/code/rspec-dev/repos/rspec-core/lib/rspec/core/runner.rb:116:in `block in run_specs'
     # /Users/bti/code/rspec-dev/repos/rspec-core/lib/rspec/core/reporter.rb:74:in `report'
     # /Users/bti/code/rspec-dev/repos/rspec-core/lib/rspec/core/runner.rb:115:in `run_specs'
     # /Users/bti/code/rspec-dev/repos/rspec-core/lib/rspec/core/runner.rb:89:in `run'
     # /Users/bti/code/rspec-dev/repos/rspec-core/lib/rspec/core/runner.rb:71:in `run'
     # /Users/bti/code/rspec-dev/repos/rspec-core/lib/rspec/core/runner.rb:45:in `invoke'
     # /Users/bti/code/rspec-dev/repos/rspec-core/exe/rspec:4:in `<main>'
     # org/jruby/RubyKernel.java:1008:in `load'
     # /Users/bti/.rvm/gems/jruby-9.2.6.0/bin/rspec:1:in `(root)'
     # org/jruby/RubyKernel.java:1047:in `eval'
     # /Users/bti/.rvm/gems/jruby-9.2.6.0/bin/jruby_executable_hooks:24:in `<main>'

Finished in 0.06331 seconds (files took 9.71 seconds to load)
1 example, 1 failure
```

I can open a new issue if needed.

**Comment by dr-itz** [comment]
>      # /Users/bti/.rvm/gems/jruby-9.2.6.0/gems/activerecord-jdbc-adapter-50.0/lib/arjdbc/sqlite3/adapter.rb:295:in `block in columns'
>      # org/jruby/RubyArray.java:2577:in `map'
>      # /Users/bti/.rvm/gems/jruby-9.2.6.0/gems/activerecord-jdbc-adapter-50.0/lib/arjdbc/sqlite3/adapter.rb:282:in `columns'
>      # /Users/bti/.rvm/gems/jruby-9.2.6.0/gems/activerecord-6.0.0/lib/active_record/connection_adapters/schema_cache.rb:76:in `columns'

here you see Rails 6.0 with arjdbc-50.0, but you want version 60.0.rc1 😉.

We should also do a final release now that Rails 6.0 is finally out. Meanwhile please try arjdbc 60.0.rc1 and report back. Thanks.

**Comment by benoittgt** [comment]
Thanks for the fast answer. 🙏

**Comment by benoittgt** [comment]
It is working with 60.0.rc1. Thanks 😉

**Comment by dr-itz** [comment]
With 60.0 out, this can be considered done 🎉
