### ISSUE TITLE
PostgreSQL JDBC driver update (42.2+) to support SCRAM-SHA-256 auth

### ISSUE THREAD

**Issue by aleksandrs-ledovskis** [jruby/activerecord-jdbc-adapter#995]
At the moment `jdbc-postgres` bundles PostgreSQL JDBC driver v42.1.4 which was released in 2017. The [latest version](https://jdbc.postgresql.org/) is v42.2.5.

Since [42.2](https://jdbc.postgresql.org/documentation/changelog.html#version_42.2.0) a `SCRAM-SHA-256` authentication protocol support has been added.

Currently the attempt to connect to SCRAM-SHA-256 enforced DB results in error:

```
ActiveRecord::JDBCError: The authentication type 10 is not supported. Check that you have configured the pg_hba.conf file to include the client's IP address or subnet, and that it is using an authentication scheme supported by the driver.
                              initialize at arjdbc/jdbc/RubyJdbcConnection.java:551
                              initialize at /gems/gems/activerecord-jdbc-adapter-52.1-java/lib/arjdbc/abstract/core.rb:19
```

**Comment by aleksandrs-ledovskis** [comment]
Fixed in `50-stable`. Waiting for merges to `51-stable`,`52-stable` and `master` before closing this issue.

**Comment by aleksandrs-ledovskis** [comment]
Closed. The gem's versions v52.2, v51.3 and v50.3 all contain the fix.

**Comment by aleksandrs-ledovskis** [comment]
@enebo Could you please check, it seems that [jdbc-postgres](https://rubygems.org/gems/jdbc-postgres) wasn't released with the updated JARs onboard.

**Comment by kares** [comment]
**jdbc-postgres** 42.2.5 got released, as for others - soon to follow
